apiVersion: v2
name: temporal-worker
description: A Helm chart for the Alga PSA Temporal Worker component
type: application
version: 0.1.0
appVersion: "1.0"
home: https://github.com/Nine-Minds/alga-psa
maintainers:
  - name: Alga PSA Team
    email: support@algapsa.com
keywords:
  - temporal
  - workflow
  - worker
  - alga-psa
sources:
  - https://github.com/Nine-Minds/alga-psa