import { knex, type Knex } from 'knex';

export function applicationTestDatabaseConfig(env: Record<string, string | undefined> = process.env): Knex.Config {
  if (env.E2E_DATABASE_ISOLATED !== 'true') {
    throw new Error('API E2E tests require E2E_DATABASE_ISOLATED=true and an owned application database');
  }
  for (const name of ['E2E_DB_HOST', 'E2E_DB_PORT', 'E2E_DB_NAME', 'E2E_DB_USER', 'E2E_DB_PASSWORD']) {
    if (!env[name]?.trim()) throw new Error(`API E2E tests require explicit ${name}`);
  }
  const port = Number(env.E2E_DB_PORT);
  if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('Invalid E2E_DB_PORT');
  if (!/^[a-z0-9_]+$/i.test(env.E2E_DB_NAME!) || /^(prod|production|sebastian_prod|postgres|template0|template1)$/i.test(env.E2E_DB_NAME!)) {
    throw new Error('API E2E tests require a dedicated test database name');
  }
  if (env.E2E_DATABASE_ID !== undefined && !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(env.E2E_DATABASE_ID)) {
    throw new Error('E2E_DATABASE_ID must be a UUID v4 generated by the environment owner');
  }
  if (/^server$/i.test(env.E2E_DB_NAME!) &&
      (!env.E2E_DATABASE_ID || !['127.0.0.1', '::1', 'localhost'].includes(env.E2E_DB_HOST!))) {
    throw new Error('The default application database requires a loopback connection and verified E2E_DATABASE_ID');
  }
  return { client: 'pg', connection: {
    host: env.E2E_DB_HOST, port, database: env.E2E_DB_NAME,
    user: env.E2E_DB_USER, password: env.E2E_DB_PASSWORD,
  }, pool: { min: 0, max: 5 } };
}

// Connect only: schema creation and migration belong to the application stack.
export async function connectApplicationTestDatabase(
  env: Record<string, string | undefined> = process.env,
): Promise<Knex> {
  const db = knex(applicationTestDatabaseConfig(env));
  if (env.E2E_DATABASE_ID !== undefined) {
    try {
      // This marker is provisioned by the owner of the disposable stack, never
      // by a test connection. Qualify the schema to avoid search_path fallback.
      const result = await db.raw(
        'SELECT environment_id::text FROM public.alga_test_environment_ownership WHERE singleton = true AND database_name = current_database()',
      );
      if (result.rows.length !== 1 || result.rows[0].environment_id !== env.E2E_DATABASE_ID.toLowerCase()) {
        throw new Error('Database ownership marker does not match this test environment');
      }
    } catch (cause) {
      await db.destroy();
      throw new Error('API E2E database ownership verification failed; no fixtures were created', { cause });
    }
  }
  return db;
}
