import { describe, expect, it } from 'vitest';

import { applyCatalogActionChoiceToStep, isAutoGeneratedSaveAsName } from '../groupedActionSelection';
import type { NodeStep } from '@shared/workflow/runtime/client';
import type { WorkflowDesignerCatalogAction } from '@shared/workflow/runtime/designer/actionCatalog';

const generateSaveAsName = (actionId: string) => actionId.replace(/\./g, '_');

const createAction: WorkflowDesignerCatalogAction = {
  id: 'tickets.create',
  version: 1,
  label: 'Create Ticket',
  description: 'Create a ticket.',
  inputFieldNames: ['summary', 'board_id', 'priority_id'],
  outputFieldNames: ['ticket_id'],
};

const updateAction: WorkflowDesignerCatalogAction = {
  id: 'tickets.update_fields',
  version: 2,
  label: 'Update Ticket',
  description: 'Update a ticket.',
  inputFieldNames: ['ticket_id', 'summary'],
  outputFieldNames: ['ticket_id'],
};

describe('grouped action selection helpers', () => {
  it('preserves still-valid input mappings, drops stale ones, and refreshes auto-generated saveAs names', () => {
    const step: NodeStep = {
      id: 'step-1',
      type: 'action.call',
      name: 'Ticket',
      config: {
        actionId: 'tickets.create',
        version: 1,
        saveAs: 'tickets_create',
        inputMapping: {
          summary: 'Keep me',
          board_id: 'drop-me',
        },
      },
    };

    const nextStep = applyCatalogActionChoiceToStep(step, updateAction, {
      generateSaveAsName,
      currentGroupLabel: 'Ticket',
      currentActionLabel: 'Create Ticket',
      nextGroupLabel: 'Ticket',
    });

    expect(nextStep.name).toBe('Update Ticket');
    expect(nextStep.config).toMatchObject({
      actionId: 'tickets.update_fields',
      version: 2,
      saveAs: 'tickets_update_fields',
      inputMapping: {
        summary: 'Keep me',
      },
    });
    expect((nextStep.config as Record<string, unknown>).inputMapping).not.toHaveProperty('board_id');
  });

  it('preserves custom step names and custom saveAs values when changing actions', () => {
    const step: NodeStep = {
      id: 'step-2',
      type: 'action.call',
      name: 'Critical ticket update',
      config: {
        actionId: 'tickets.create',
        version: 1,
        saveAs: 'criticalTicket',
        inputMapping: {
          summary: 'Keep me',
          board_id: 'drop-me',
        },
      },
    };

    const nextStep = applyCatalogActionChoiceToStep(step, updateAction, {
      generateSaveAsName,
      currentGroupLabel: 'Ticket',
      currentActionLabel: 'Create Ticket',
      nextGroupLabel: 'Ticket',
    });

    expect(nextStep.name).toBe('Critical ticket update');
    expect(nextStep.config).toMatchObject({
      saveAs: 'criticalTicket',
      inputMapping: {
        summary: 'Keep me',
      },
    });
  });

  it('supports clearing a chosen action back to the grouped step state', () => {
    const step: NodeStep = {
      id: 'step-3',
      type: 'action.call',
      name: 'Create Ticket',
      config: {
        designerGroupKey: 'ticket',
        designerTileKind: 'core-object',
        actionId: 'tickets.create',
        version: 1,
        saveAs: 'tickets_create',
        inputMapping: {
          summary: 'test',
        },
      },
    };

    const nextStep = applyCatalogActionChoiceToStep(step, null, {
      generateSaveAsName,
      currentGroupLabel: 'Ticket',
      currentActionLabel: 'Create Ticket',
      nextGroupLabel: 'Ticket',
    });

    expect(nextStep.name).toBe('Ticket');
    expect(nextStep.config).toMatchObject({
      designerGroupKey: 'ticket',
      designerTileKind: 'core-object',
    });
    expect(nextStep.config).not.toHaveProperty('actionId');
    expect(nextStep.config).not.toHaveProperty('version');
    expect(nextStep.config).not.toHaveProperty('saveAs');
    expect(nextStep.config).not.toHaveProperty('inputMapping');
  });

  it('detects when a saveAs value was auto-generated from an action id', () => {
    expect(isAutoGeneratedSaveAsName('tickets_create', createAction.id, generateSaveAsName)).toBe(true);
    expect(isAutoGeneratedSaveAsName('customTicket', createAction.id, generateSaveAsName)).toBe(false);
    expect(isAutoGeneratedSaveAsName(undefined, createAction.id, generateSaveAsName)).toBe(false);
  });
});
