import { describe, expect, it } from 'vitest';
import type { NodeStep, Step } from '@alga-psa/workflows/runtime/client';

import {
  collectSaveAsNames,
  generateSaveAsName,
  generateUniqueSaveAsName,
  isSaveAsNameFromBase,
  uniqueSaveAsName,
} from '../workflowSaveAsNames';
import { applyCatalogActionChoiceToStep, isAutoGeneratedSaveAsName } from '../groupedActionSelection';

const addComment = (id: string, saveAs?: string): NodeStep => ({
  id,
  type: 'action.call',
  config: { actionId: 'tickets.add_comment', version: 1, ...(saveAs ? { saveAs } : {}) },
});

const workflowWithCommentInThen = (): Step[] => [
  {
    id: 'if-1',
    type: 'control.if',
    condition: { $expr: 'true' },
    then: [addComment('then-comment', 'ticketsAddCommentResult')],
    else: [],
  } as Step,
];

describe('workflow saveAs default names', () => {
  it('derives the base name from the action id', () => {
    expect(generateSaveAsName('tickets.add_comment')).toBe('ticketsAddCommentResult');
    expect(generateSaveAsName('lookup_threading_headers')).toBe('threadingHeadersResult');
  });

  it('collects names from every branch and can leave one step out', () => {
    const steps: Step[] = [
      addComment('top', 'first'),
      {
        id: 'try-1',
        type: 'control.tryCatch',
        try: [addComment('in-try', 'second')],
        catch: [addComment('in-catch', 'third')],
      } as Step,
    ];
    expect(collectSaveAsNames(steps)).toEqual(['first', 'second', 'third']);
    expect(collectSaveAsNames(steps, { excludeStepId: 'in-try' })).toEqual(['first', 'third']);
  });

  it('suffixes 2, 3… until the name is free', () => {
    expect(uniqueSaveAsName('result', [])).toBe('result');
    expect(uniqueSaveAsName('result', ['result'])).toBe('result2');
    expect(uniqueSaveAsName('result', ['result', 'result2'])).toBe('result3');
  });

  it('gives a second Add Ticket Comment (in the Else branch) its own default name', () => {
    expect(generateUniqueSaveAsName('tickets.add_comment', workflowWithCommentInThen()))
      .toBe('ticketsAddCommentResult2');
  });

  it("doesn't count the renamed step's own name as taken", () => {
    expect(generateUniqueSaveAsName('tickets.add_comment', workflowWithCommentInThen(), { excludeStepId: 'then-comment' }))
      .toBe('ticketsAddCommentResult');
  });

  it('recognises suffixed defaults as generated names', () => {
    expect(isSaveAsNameFromBase('ticketsAddCommentResult', 'ticketsAddCommentResult')).toBe(true);
    expect(isSaveAsNameFromBase('ticketsAddCommentResult2', 'ticketsAddCommentResult')).toBe(true);
    expect(isSaveAsNameFromBase('ticketsAddCommentResult12', 'ticketsAddCommentResult')).toBe(true);
    expect(isSaveAsNameFromBase('ticketsAddCommentResult1', 'ticketsAddCommentResult')).toBe(false);
    expect(isSaveAsNameFromBase('ticketsAddCommentResultX', 'ticketsAddCommentResult')).toBe(false);
    expect(isAutoGeneratedSaveAsName('ticketsAddCommentResult3', 'tickets.add_comment', generateSaveAsName)).toBe(true);
  });

  it('keeps a grouped action choice from reusing another step\'s output name', () => {
    const elseStep: NodeStep = {
      id: 'else-comment',
      type: 'action.call',
      config: { designerGroupKey: 'tickets', designerTileKind: 'core-object' },
    };
    const next = applyCatalogActionChoiceToStep(elseStep, {
      id: 'tickets.add_comment',
      version: 1,
      label: 'Add Comment',
      description: 'Add a comment.',
      inputFieldNames: ['ticket_id', 'body'],
      outputFieldNames: ['comment_id'],
    }, {
      generateSaveAsName,
      takenSaveAsNames: collectSaveAsNames(workflowWithCommentInThen(), { excludeStepId: elseStep.id }),
    });
    expect((next.config as Record<string, unknown>).saveAs).toBe('ticketsAddCommentResult2');
  });
});
