{{- if and .Values.devEnv.enabled .Values.devEnv.aiAutomation.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ai-api
  namespace: {{ .Values.devEnv.namespace }}
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-api-alias
spec:
  type: ExternalName
  externalName: {{ include "sebastian.fullname" . }}-ai-api.{{ .Values.devEnv.namespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.devEnv.aiAutomation.api.service.port }}
      targetPort: {{ .Values.devEnv.aiAutomation.api.service.port }}
      protocol: TCP
      name: http
{{- end }}