{{- if and .Values.devEnv.enabled .Values.devEnv.aiAutomation.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ai-web
  namespace: {{ .Values.devEnv.namespace }}
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-web-alias
spec:
  type: ExternalName
  externalName: {{ include "sebastian.fullname" . }}-ai-web.{{ .Values.devEnv.namespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.devEnv.aiAutomation.web.service.port }}
      targetPort: {{ .Values.devEnv.aiAutomation.web.service.port }}
      protocol: TCP
      name: http
{{- end }}