version: '3.8'

x-environment: &shared-environment
  # ---- APP -------
  VERSION: ${VERSION}
  APP_NAME: ${APP_NAME}
  APP_ENV: ${APP_ENV:-production}
  NODE_ENV: ${APP_ENV:-production}
  HOST: ${HOST}
  VERIFY_EMAIL_ENABLED: ${VERIFY_EMAIL_ENABLED:-false}

  # ---- REDIS ----
  REDIS_HOST: ${REDIS_HOST:-redis}
  REDIS_PORT: ${REDIS_PORT:-6379}

  # ---- DATABASE ----
  DB_TYPE: ${DB_TYPE}
  DB_HOST: postgres
  DB_PORT: ${DB_PORT:-5432}
  DB_NAME_SERVER: server
  DB_USER_SERVER: app_user
  POSTGRES_USER: postgres

  # ---- LOGGING ----
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  LOG_IS_FORMAT_JSON: ${LOG_IS_FORMAT_JSON:-false}
  LOG_IS_FULL_DETAILS: ${LOG_IS_FULL_DETAILS:-false}
  LOG_ENABLED_FILE_LOGGING: ${LOG_ENABLED_FILE_LOGGING}
  LOG_DIR_PATH: ${LOG_DIR_PATH}
  LOG_ENABLED_EXTERNAL_LOGGING: ${LOG_ENABLED_EXTERNAL_LOGGING}
  LOG_EXTERNAL_HTTP_HOST: ${LOG_EXTERNAL_HTTP_HOST}
  LOG_EXTERNAL_HTTP_PORT: ${LOG_EXTERNAL_HTTP_PORT}
  LOG_EXTERNAL_HTTP_PATH: ${LOG_EXTERNAL_HTTP_PATH}
  LOG_EXTERNAL_HTTP_LEVEL: ${LOG_EXTERNAL_HTTP_LEVEL}
  LOG_EXTERNAL_HTTP_TOKEN: ${LOG_EXTERNAL_HTTP_TOKEN}

  # ---- HOCUSPOCUS ----
  HOCUSPOCUS_PORT: ${HOCUSPOCUS_PORT}
  HOCUSPOCUS_URL: ${HOCUSPOCUS_URL}

  # ---- EMAIL ----
  EMAIL_ENABLE: ${EMAIL_ENABLE:-false}
  EMAIL_FROM: ${EMAIL_FROM:-noreply@example.com}
  EMAIL_HOST: ${EMAIL_HOST}
  EMAIL_PORT: ${EMAIL_PORT:-587}
  EMAIL_USERNAME: ${EMAIL_USERNAME:-noreply@example.com}

  # ---- CRYPTO ----
  CRYPTO_SALT_BYTES: ${SALT_BYTES}
  CRYPTO_ITERATION: ${ITERATION}
  CRYPTO_KEY_LENGTH: ${KEY_LENGTH}
  CRYPTO_ALGORITHM: ${ALGORITHM}

  # ---- TOKEN ----
  TOKEN_EXPIRES: ${TOKEN_EXPIRES}

  # ---- AUTH ----
  NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
  NEXTAUTH_SESSION_EXPIRES: ${NEXTAUTH_SESSION_EXPIRES:-86400}

  # ---- DEPLOY INFO  ----
  PROJECT_NAME: ${PROJECT_NAME}
  EXPOSE_DB_PORT: ${EXPOSE_DB_PORT:-5432}
  EXPOSE_HOCUSPOCUS_PORT: ${EXPOSE_HOCUSPOCUS_PORT:-1234}
  EXPOSE_REDIS_PORT: ${EXPOSE_REDIS_PORT:-6379}
  EXPOSE_SERVER_PORT: ${EXPOSE_SERVER_PORT:-3000}

secrets:
  db_password_server:
    file: ./secrets/db_password_server
  db_password_hocuspocus:
    file: ./secrets/db_password_hocuspocus
  postgres_password:
    file: ./secrets/postgres_password
  redis_password:
    file: ./secrets/redis_password
  email_password:
    file: ./secrets/email_password
  crypto_key:
    file: ./secrets/crypto_key
  token_secret_key:
    file: ./secrets/token_secret_key
  nextauth_secret:
    file: ./secrets/nextauth_secret
  google_oauth_client_id:
    file: ./secrets/google_oauth_client_id
  google_oauth_client_secret:
    file: ./secrets/google_oauth_client_secret
  alga_auth_key:
    file: ./secrets/alga_auth_key

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: ${APP_NAME:-sebastian}_postgres
    environment:
      <<: *shared-environment
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "${EXPOSE_DB_PORT:-5432}:5432"
    networks:
      - app-network

  redis:
    build:
      context: .
      dockerfile: redis/Dockerfile
    container_name: ${APP_NAME:-sebastian}_redis
    environment:
      <<: *shared-environment
    ports:
      - '${EXPOSE_REDIS_PORT:-6379}:6379'
    secrets:
      - redis_password
    networks:
      - app-network

networks:
  app-network:
    name: ${APP_NAME:-sebastian}_app-network
    driver: bridge
