{{- if .Values.config.storage.providers.local.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sebastian.fullname" . }}-local-storage
  namespace: {{ include "sebastian.namespace" . }}
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
spec:
  {{- $existingPVC := lookup "v1" "PersistentVolumeClaim" (include "sebastian.namespace" .) (printf "%s-local-storage" (include "sebastian.fullname" .)) }}
  {{- if and $existingPVC $existingPVC.spec.volumeName }}
  volumeName: {{ $existingPVC.spec.volumeName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
