{{- if not .Values.persistence.keepPvcOnUninstall }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "sebastian.fullname" . }}-pvc-delete"
  namespace: {{ include "sebastian.namespace" . }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "sebastian.fullname" . }}-pvc-delete"
    spec:
      serviceAccountName: "{{ include "sebastian.fullname" . }}-pvc-delete-sa"
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl delete pvc db-volume-claim -n {{ include "sebastian.namespace" . }}
{{- end }}
---
{{- if not .Values.persistence.keepPvcOnUninstall }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "sebastian.fullname" . }}-pvc-delete-sa"
  namespace: {{ include "sebastian.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "sebastian.fullname" . }}-pvc-delete-role"
  namespace: {{ include "sebastian.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "sebastian.fullname" . }}-pvc-delete-rolebinding"
  namespace: {{ include "sebastian.namespace" . }}
subjects:
- kind: ServiceAccount
  name: "{{ include "sebastian.fullname" . }}-pvc-delete-sa"
roleRef:
  kind: Role
  name: "{{ include "sebastian.fullname" . }}-pvc-delete-role"
  apiGroup: rbac.authorization.k8s.io
{{- end }}