{{- if and .Values.config.storage.providers.s3.enabled (or .Values.config.storage.providers.s3.access_key .Values.config.storage.providers.s3.secret_key) }}
apiVersion: v1
kind: Secret
metadata:
  name: storage-credentials
  namespace: {{ include "sebastian.namespace" . }}
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.storage.providers.s3.access_key }}
  S3_ACCESS_KEY: {{ .Values.config.storage.providers.s3.access_key | quote }}
  {{- end }}
  {{- if .Values.config.storage.providers.s3.secret_key }}
  S3_SECRET_KEY: {{ .Values.config.storage.providers.s3.secret_key | quote }}
  {{- end }}
{{- end }}

