{{- if and .Values.tenantSecrets.persistence.enabled (not .Values.tenantSecrets.persistence.existingClaim) (not .Values.sharedTenantSecrets.enabled) (not .Values.devEnv.enabled) (not (include "sebastian.hostedEnvEnabled" .)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sebastian.fullname" . }}-tenant-secrets
  namespace: {{ include "sebastian.namespace" . }}
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
  {{- with .Values.tenantSecrets.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $existingPVC := lookup "v1" "PersistentVolumeClaim" (include "sebastian.namespace" .) (printf "%s-tenant-secrets" (include "sebastian.fullname" .)) }}
  {{- if and $existingPVC $existingPVC.spec.volumeName }}
  volumeName: {{ $existingPVC.spec.volumeName }}
  {{- end }}
  accessModes:
    {{- range .Values.tenantSecrets.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.tenantSecrets.persistence.size | quote }}
  {{- if .Values.tenantSecrets.persistence.storageClass }}
  {{- if (eq "-" .Values.tenantSecrets.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.tenantSecrets.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
