namespace: msp
enabled: true
replicaCount: 1

image:
  repository: ghcr.io/nine-minds/temporal-worker
  tag: latest
  pullPolicy: IfNotPresent
  is_private: false
  credentials: ""

temporal:
  address: temporal-frontend.msp.svc.cluster.local:7233
  namespace: default
  taskQueue: tenant-workflows,portal-domain-workflows,email-domain-workflows

db:
  host: pgbouncer.msp.svc.cluster.local
  port: "6432"
  serverDatabase: server
  user: app_user_pgbouncer
  serverPasswordSecret:
    name: db-credentials
    key: DB_PASSWORD_PGBOUNCER
  adminPasswordSecret:
    name: db-credentials
    key: DB_PASSWORD_SUPERUSER

applicationUrl: http://alga-core.msp.svc.cluster.local:3000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

auth:
  nextauthSecretSecret:
    name: alga-core-sebastian-secrets
    key: NEXTAUTH_SECRET

portalDomain:
  certificateNamespace: ""
  gatewayNamespace: ""
  secretReplicationEnabled: false
  baseVirtualService: ""
