{{- if and .Values.enabled (not .Values.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal-worker.fullname" . }}-secrets
  namespace: {{ include "temporal-worker.namespace" . }}
  labels:
    {{- include "temporal-worker.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-worker
type: Opaque
stringData:
  INTERNAL_API_SHARED_SECRET: {{ .Values.secrets.internalApiSharedSecret | quote }}
  ALGA_AUTH_KEY: {{ .Values.secrets.algaAuthKey | quote }}
{{- end }}