import type { InputMapping, NodeStep, WorkflowDesignerCatalogAction } from '@alga-psa/workflows/runtime';
import {
  isWorkflowAiInferAction,
  isWorkflowComposeTextAction,
} from '@alga-psa/workflows/authoring';

type GroupedActionStepConfig = {
  actionId?: string;
  version?: number;
  inputMapping?: InputMapping;
  saveAs?: string;
};

const asRecord = (value: unknown): Record<string, unknown> | undefined =>
  value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;

const asInputMapping = (value: unknown): InputMapping | undefined => {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return undefined;
  }
  return value as InputMapping;
};

const filterInputMapping = (
  mapping: InputMapping | undefined,
  allowedFieldNames: string[]
): InputMapping | undefined => {
  if (!mapping) return undefined;

  const allowedFieldSet = new Set(allowedFieldNames);
  const filteredEntries = Object.entries(mapping).filter(([fieldName]) => allowedFieldSet.has(fieldName));
  if (filteredEntries.length === 0) {
    return undefined;
  }
  return Object.fromEntries(filteredEntries);
};

export const isAutoGeneratedSaveAsName = (
  saveAs: string | undefined,
  actionId: string | undefined,
  generateSaveAsName: (actionId: string) => string
): boolean => {
  if (!saveAs || !actionId) return false;
  return saveAs === generateSaveAsName(actionId);
};

export const applyCatalogActionChoiceToStep = (
  step: NodeStep,
  nextAction: WorkflowDesignerCatalogAction | null,
  options: {
    generateSaveAsName: (actionId: string) => string;
    currentGroupLabel?: string;
    currentActionLabel?: string;
    nextGroupLabel?: string;
  }
): NodeStep => {
  const existingConfig = asRecord(step.config) ?? {};
  const currentConfig = existingConfig as GroupedActionStepConfig;
  const currentActionId = typeof currentConfig.actionId === 'string' ? currentConfig.actionId : undefined;
  const currentSaveAs = typeof currentConfig.saveAs === 'string' && currentConfig.saveAs.trim().length > 0
    ? currentConfig.saveAs.trim()
    : undefined;
  const shouldRefreshSaveAs =
    !currentSaveAs ||
    isAutoGeneratedSaveAsName(currentSaveAs, currentActionId, options.generateSaveAsName);

  const nextConfig: Record<string, unknown> = { ...existingConfig };
  if (nextAction) {
    nextConfig.actionId = nextAction.id;
    nextConfig.version = nextAction.version;
    const filteredInputMapping = filterInputMapping(
      asInputMapping(currentConfig.inputMapping),
      nextAction.inputFieldNames
    );
    if (filteredInputMapping) {
      nextConfig.inputMapping = filteredInputMapping;
    } else {
      delete nextConfig.inputMapping;
    }
    if (shouldRefreshSaveAs) {
      nextConfig.saveAs = options.generateSaveAsName(nextAction.id);
    }
  } else {
    delete nextConfig.actionId;
    delete nextConfig.version;
    delete nextConfig.inputMapping;
    if (shouldRefreshSaveAs) {
      delete nextConfig.saveAs;
    }
  }

  const nextActionId = nextAction?.id;
  if (!isWorkflowAiInferAction(nextActionId)) {
    delete nextConfig.aiOutputSchemaMode;
    delete nextConfig.aiOutputSchema;
    delete nextConfig.aiOutputSchemaText;
  }
  if (!isWorkflowComposeTextAction(nextActionId)) {
    delete nextConfig.outputs;
  }

  const currentName = step.name?.trim() ?? '';
  const autoManagedNames = new Set(
    [options.currentGroupLabel, options.currentActionLabel].filter(
      (value): value is string => typeof value === 'string' && value.trim().length > 0
    )
  );
  const shouldRefreshName = currentName.length === 0 || autoManagedNames.has(currentName);
  const nextName = nextAction?.label ?? options.nextGroupLabel ?? options.currentGroupLabel ?? step.name;

  return {
    ...step,
    name: shouldRefreshName ? nextName : step.name,
    config: Object.keys(nextConfig).length > 0 ? nextConfig : undefined,
  };
};
