apiVersion: v1
kind: Namespace
metadata:
  name: alga-appliance-support
  labels:
    app.kubernetes.io/part-of: alga-appliance
    alga.nineminds.com/appliance-plane: support
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
