import type { EmitterContracts } from './registryTypes';
import { pendingMigration, schemaNotRegistered } from './registryTypes';
import { ticketContracts } from './contracts/tickets';

/**
 * Emitter contract registry. One entry per workflow-catalogued event type.
 *
 * The mapped type makes this exhaustive at compile time: adding an event to
 * WORKFLOW_EVENT_CATALOG without an entry here fails `typecheck`.
 *
 * - `covered`: every case calls the real exported builder the product emitter uses, and the
 *   resulting payload must pass the schema the workflow worker uses.
 * - `known-drift`: the emitter fails the contract today (or its builder is not extracted yet).
 *   Tracked against a ticket; runs under it.fails.
 * - `no-product-emitter`: the catalog advertises the trigger but nothing fires it.
 */
export const emitterContracts: EmitterContracts = {
  // ---- tickets ----
  ...ticketContracts,
  // ---- projects ----
  PROJECT_CREATED: pendingMigration('PROJECT_CREATED', 'projects'),
  PROJECT_APPROVAL_GRANTED: pendingMigration('PROJECT_APPROVAL_GRANTED', 'projects'),
  PROJECT_APPROVAL_REJECTED: pendingMigration('PROJECT_APPROVAL_REJECTED', 'projects'),
  PROJECT_APPROVAL_REQUESTED: pendingMigration('PROJECT_APPROVAL_REQUESTED', 'projects'),
  PROJECT_STATUS_CHANGED: pendingMigration('PROJECT_STATUS_CHANGED', 'projects'),
  PROJECT_TASK_ASSIGNED: pendingMigration('PROJECT_TASK_ASSIGNED', 'projects'),
  PROJECT_TASK_COMPLETED: pendingMigration('PROJECT_TASK_COMPLETED', 'projects'),
  PROJECT_TASK_CREATED: pendingMigration('PROJECT_TASK_CREATED', 'projects'),
  PROJECT_TASK_DEPENDENCY_BLOCKED: pendingMigration('PROJECT_TASK_DEPENDENCY_BLOCKED', 'projects'),
  PROJECT_TASK_DEPENDENCY_UNBLOCKED: pendingMigration('PROJECT_TASK_DEPENDENCY_UNBLOCKED', 'projects'),
  PROJECT_TASK_STATUS_CHANGED: pendingMigration('PROJECT_TASK_STATUS_CHANGED', 'projects'),
  PROJECT_UPDATED: pendingMigration('PROJECT_UPDATED', 'projects'),
  // ---- scheduling ----
  APPOINTMENT_ASSIGNED: pendingMigration('APPOINTMENT_ASSIGNED', 'scheduling'),
  APPOINTMENT_CANCELED: pendingMigration('APPOINTMENT_CANCELED', 'scheduling'),
  APPOINTMENT_COMPLETED: pendingMigration('APPOINTMENT_COMPLETED', 'scheduling'),
  APPOINTMENT_CREATED: pendingMigration('APPOINTMENT_CREATED', 'scheduling'),
  APPOINTMENT_NO_SHOW: pendingMigration('APPOINTMENT_NO_SHOW', 'scheduling'),
  APPOINTMENT_RESCHEDULED: pendingMigration('APPOINTMENT_RESCHEDULED', 'scheduling'),
  CAPACITY_THRESHOLD_REACHED: pendingMigration('CAPACITY_THRESHOLD_REACHED', 'scheduling'),
  SCHEDULE_BLOCK_CREATED: pendingMigration('SCHEDULE_BLOCK_CREATED', 'scheduling'),
  SCHEDULE_BLOCK_DELETED: pendingMigration('SCHEDULE_BLOCK_DELETED', 'scheduling'),
  TECHNICIAN_ARRIVED: pendingMigration('TECHNICIAN_ARRIVED', 'scheduling'),
  TECHNICIAN_CHECKED_OUT: pendingMigration('TECHNICIAN_CHECKED_OUT', 'scheduling'),
  TECHNICIAN_DISPATCHED: pendingMigration('TECHNICIAN_DISPATCHED', 'scheduling'),
  TECHNICIAN_EN_ROUTE: pendingMigration('TECHNICIAN_EN_ROUTE', 'scheduling'),
  // ---- billing ----
  INVOICE_GENERATED: pendingMigration('INVOICE_GENERATED', 'billing'),
  INVOICE_FINALIZED: pendingMigration('INVOICE_FINALIZED', 'billing'),
  CONTRACT_CREATED: pendingMigration('CONTRACT_CREATED', 'billing'),
  CONTRACT_RENEWAL_UPCOMING: pendingMigration('CONTRACT_RENEWAL_UPCOMING', 'billing'),
  CONTRACT_STATUS_CHANGED: pendingMigration('CONTRACT_STATUS_CHANGED', 'billing'),
  CONTRACT_UPDATED: pendingMigration('CONTRACT_UPDATED', 'billing'),
  CREDIT_NOTE_APPLIED: pendingMigration('CREDIT_NOTE_APPLIED', 'billing'),
  CREDIT_NOTE_CREATED: pendingMigration('CREDIT_NOTE_CREATED', 'billing'),
  CREDIT_NOTE_VOIDED: pendingMigration('CREDIT_NOTE_VOIDED', 'billing'),
  INVOICE_DUE_DATE_CHANGED: pendingMigration('INVOICE_DUE_DATE_CHANGED', 'billing'),
  INVOICE_OVERDUE: pendingMigration('INVOICE_OVERDUE', 'billing'),
  INVOICE_SENT: pendingMigration('INVOICE_SENT', 'billing'),
  INVOICE_STATUS_CHANGED: pendingMigration('INVOICE_STATUS_CHANGED', 'billing'),
  INVOICE_WRITTEN_OFF: pendingMigration('INVOICE_WRITTEN_OFF', 'billing'),
  PAYMENT_APPLIED: pendingMigration('PAYMENT_APPLIED', 'billing'),
  PAYMENT_FAILED: pendingMigration('PAYMENT_FAILED', 'billing'),
  PAYMENT_RECORDED: pendingMigration('PAYMENT_RECORDED', 'billing'),
  PAYMENT_REFUNDED: pendingMigration('PAYMENT_REFUNDED', 'billing'),
  RECURRING_BILLING_RUN_COMPLETED: pendingMigration('RECURRING_BILLING_RUN_COMPLETED', 'billing'),
  RECURRING_BILLING_RUN_FAILED: pendingMigration('RECURRING_BILLING_RUN_FAILED', 'billing'),
  RECURRING_BILLING_RUN_STARTED: pendingMigration('RECURRING_BILLING_RUN_STARTED', 'billing'),
  PROJECT_MILESTONE_READY: schemaNotRegistered('PROJECT_MILESTONE_READY', 'payload.ProjectMilestoneReady.v1'),
  PROJECT_BUDGET_THRESHOLD_REACHED: schemaNotRegistered('PROJECT_BUDGET_THRESHOLD_REACHED', 'payload.ProjectBudgetThresholdReached.v1'),
  PROJECT_BUDGET_EXCEEDED: schemaNotRegistered('PROJECT_BUDGET_EXCEEDED', 'payload.ProjectBudgetExceeded.v1'),
  PROJECT_BILLING_CONFIG_CREATED: schemaNotRegistered('PROJECT_BILLING_CONFIG_CREATED', 'payload.ProjectBillingConfigCreated.v1'),
  PROJECT_BILLING_CONFIG_UPDATED: schemaNotRegistered('PROJECT_BILLING_CONFIG_UPDATED', 'payload.ProjectBillingConfigUpdated.v1'),
  PROJECT_BILLING_CONFIG_DELETED: schemaNotRegistered('PROJECT_BILLING_CONFIG_DELETED', 'payload.ProjectBillingConfigDeleted.v1'),
  PROJECT_BILLING_SCHEDULE_ENTRY_CREATED: schemaNotRegistered('PROJECT_BILLING_SCHEDULE_ENTRY_CREATED', 'payload.ProjectBillingScheduleEntryCreated.v1'),
  PROJECT_BILLING_SCHEDULE_ENTRY_UPDATED: schemaNotRegistered('PROJECT_BILLING_SCHEDULE_ENTRY_UPDATED', 'payload.ProjectBillingScheduleEntryUpdated.v1'),
  PROJECT_BILLING_SCHEDULE_STATUS_CHANGED: schemaNotRegistered('PROJECT_BILLING_SCHEDULE_STATUS_CHANGED', 'payload.ProjectBillingScheduleStatusChanged.v1'),
  PROJECT_BILLING_SCHEDULE_ENTRY_DELETED: schemaNotRegistered('PROJECT_BILLING_SCHEDULE_ENTRY_DELETED', 'payload.ProjectBillingScheduleEntryDeleted.v1'),
  PROJECT_BILLING_PAYMENT_STATUS_CHANGED: schemaNotRegistered('PROJECT_BILLING_PAYMENT_STATUS_CHANGED', 'payload.ProjectBillingPaymentStatusChanged.v1'),
  // ---- crm ----
  CLIENT_ARCHIVED: pendingMigration('CLIENT_ARCHIVED', 'crm'),
  CLIENT_CREATED: pendingMigration('CLIENT_CREATED', 'crm'),
  CLIENT_MERGED: pendingMigration('CLIENT_MERGED', 'crm'),
  CLIENT_OWNER_ASSIGNED: pendingMigration('CLIENT_OWNER_ASSIGNED', 'crm'),
  CLIENT_STATUS_CHANGED: pendingMigration('CLIENT_STATUS_CHANGED', 'crm'),
  CLIENT_UPDATED: pendingMigration('CLIENT_UPDATED', 'crm'),
  CONTACT_ARCHIVED: pendingMigration('CONTACT_ARCHIVED', 'crm'),
  CONTACT_CREATED: pendingMigration('CONTACT_CREATED', 'crm'),
  CONTACT_MERGED: pendingMigration('CONTACT_MERGED', 'crm'),
  CONTACT_PRIMARY_SET: pendingMigration('CONTACT_PRIMARY_SET', 'crm'),
  CONTACT_UPDATED: pendingMigration('CONTACT_UPDATED', 'crm'),
  INTERACTION_LOGGED: pendingMigration('INTERACTION_LOGGED', 'crm'),
  NOTE_CREATED: pendingMigration('NOTE_CREATED', 'crm'),
  TAG_APPLIED: pendingMigration('TAG_APPLIED', 'crm'),
  TAG_DEFINITION_CREATED: pendingMigration('TAG_DEFINITION_CREATED', 'crm'),
  TAG_DEFINITION_UPDATED: pendingMigration('TAG_DEFINITION_UPDATED', 'crm'),
  TAG_REMOVED: pendingMigration('TAG_REMOVED', 'crm'),
  OPPORTUNITY_CREATED: schemaNotRegistered('OPPORTUNITY_CREATED', 'payload.OpportunityCreated.v1'),
  OPPORTUNITY_STAGE_CHANGED: schemaNotRegistered('OPPORTUNITY_STAGE_CHANGED', 'payload.OpportunityStageChanged.v1'),
  OPPORTUNITY_STATUS_CHANGED: schemaNotRegistered('OPPORTUNITY_STATUS_CHANGED', 'payload.OpportunityStatusChanged.v1'),
  OPPORTUNITY_STALLED: schemaNotRegistered('OPPORTUNITY_STALLED', 'payload.OpportunityStalled.v1'),
  OPPORTUNITY_ESCALATED: schemaNotRegistered('OPPORTUNITY_ESCALATED', 'payload.OpportunityEscalated.v1'),
  OPPORTUNITY_NEXT_ACTION_OVERDUE: schemaNotRegistered('OPPORTUNITY_NEXT_ACTION_OVERDUE', 'payload.OpportunityNextActionOverdue.v1'),
  OPPORTUNITY_SUGGESTION_CREATED: schemaNotRegistered('OPPORTUNITY_SUGGESTION_CREATED', 'payload.OpportunitySuggestionCreated.v1'),
  CLIENT_ANNIVERSARY_UPCOMING: pendingMigration('CLIENT_ANNIVERSARY_UPCOMING', 'crm'),
  // ---- documents ----
  DOCUMENT_ASSOCIATED: pendingMigration('DOCUMENT_ASSOCIATED', 'documents'),
  DOCUMENT_DELETED: pendingMigration('DOCUMENT_DELETED', 'documents'),
  DOCUMENT_DETACHED: pendingMigration('DOCUMENT_DETACHED', 'documents'),
  DOCUMENT_GENERATED: pendingMigration('DOCUMENT_GENERATED', 'documents'),
  DOCUMENT_SIGNATURE_EXPIRED: pendingMigration('DOCUMENT_SIGNATURE_EXPIRED', 'documents'),
  DOCUMENT_SIGNATURE_REQUESTED: pendingMigration('DOCUMENT_SIGNATURE_REQUESTED', 'documents'),
  DOCUMENT_SIGNED: pendingMigration('DOCUMENT_SIGNED', 'documents'),
  DOCUMENT_UPLOADED: pendingMigration('DOCUMENT_UPLOADED', 'documents'),
  FILE_UPLOADED: pendingMigration('FILE_UPLOADED', 'documents'),
  MEDIA_PROCESSING_FAILED: pendingMigration('MEDIA_PROCESSING_FAILED', 'documents'),
  MEDIA_PROCESSING_SUCCEEDED: pendingMigration('MEDIA_PROCESSING_SUCCEEDED', 'documents'),
  // ---- comms ----
  INBOUND_EMAIL_RECEIVED: pendingMigration('INBOUND_EMAIL_RECEIVED', 'comms'),
  EMAIL_PROVIDER_CONNECTED: pendingMigration('EMAIL_PROVIDER_CONNECTED', 'comms'),
  EMAIL_PROVIDER_DISCONNECTED: pendingMigration('EMAIL_PROVIDER_DISCONNECTED', 'comms'),
  ASSET_ASSIGNED: pendingMigration('ASSET_ASSIGNED', 'comms'),
  ASSET_CREATED: pendingMigration('ASSET_CREATED', 'comms'),
  ASSET_UNASSIGNED: pendingMigration('ASSET_UNASSIGNED', 'comms'),
  ASSET_UPDATED: pendingMigration('ASSET_UPDATED', 'comms'),
  ASSET_WARRANTY_EXPIRING: pendingMigration('ASSET_WARRANTY_EXPIRING', 'comms'),
  CSAT_ALERT_TRIGGERED: pendingMigration('CSAT_ALERT_TRIGGERED', 'comms'),
  EMAIL_BOUNCED: pendingMigration('EMAIL_BOUNCED', 'comms'),
  EMAIL_COMPLAINT_RECEIVED: pendingMigration('EMAIL_COMPLAINT_RECEIVED', 'comms'),
  EMAIL_DELIVERED: pendingMigration('EMAIL_DELIVERED', 'comms'),
  EMAIL_UNSUBSCRIBED: pendingMigration('EMAIL_UNSUBSCRIBED', 'comms'),
  EXTERNAL_MAPPING_CHANGED: pendingMigration('EXTERNAL_MAPPING_CHANGED', 'comms'),
  INBOUND_EMAIL_REPLY_RECEIVED: pendingMigration('INBOUND_EMAIL_REPLY_RECEIVED', 'comms'),
  INTEGRATION_CONNECTED: pendingMigration('INTEGRATION_CONNECTED', 'comms'),
  INTEGRATION_DISCONNECTED: pendingMigration('INTEGRATION_DISCONNECTED', 'comms'),
  INTEGRATION_SYNC_COMPLETED: pendingMigration('INTEGRATION_SYNC_COMPLETED', 'comms'),
  INTEGRATION_SYNC_FAILED: pendingMigration('INTEGRATION_SYNC_FAILED', 'comms'),
  INTEGRATION_SYNC_STARTED: pendingMigration('INTEGRATION_SYNC_STARTED', 'comms'),
  INTEGRATION_TOKEN_EXPIRING: pendingMigration('INTEGRATION_TOKEN_EXPIRING', 'comms'),
  INTEGRATION_TOKEN_REFRESH_FAILED: pendingMigration('INTEGRATION_TOKEN_REFRESH_FAILED', 'comms'),
  INTEGRATION_WEBHOOK_RECEIVED: pendingMigration('INTEGRATION_WEBHOOK_RECEIVED', 'comms'),
  NOTIFICATION_DELIVERED: pendingMigration('NOTIFICATION_DELIVERED', 'comms'),
  NOTIFICATION_FAILED: pendingMigration('NOTIFICATION_FAILED', 'comms'),
  NOTIFICATION_READ: pendingMigration('NOTIFICATION_READ', 'comms'),
  NOTIFICATION_SENT: pendingMigration('NOTIFICATION_SENT', 'comms'),
  OUTBOUND_EMAIL_FAILED: pendingMigration('OUTBOUND_EMAIL_FAILED', 'comms'),
  OUTBOUND_EMAIL_QUEUED: pendingMigration('OUTBOUND_EMAIL_QUEUED', 'comms'),
  OUTBOUND_EMAIL_SENT: pendingMigration('OUTBOUND_EMAIL_SENT', 'comms'),
  SURVEY_EXPIRED: pendingMigration('SURVEY_EXPIRED', 'comms'),
  SURVEY_REMINDER_SENT: pendingMigration('SURVEY_REMINDER_SENT', 'comms'),
  SURVEY_RESPONSE_RECEIVED: pendingMigration('SURVEY_RESPONSE_RECEIVED', 'comms'),
  SURVEY_SENT: pendingMigration('SURVEY_SENT', 'comms'),
  // ---- remaining ----
  INVENTORY_STOCK_LOW: schemaNotRegistered('INVENTORY_STOCK_LOW', 'payload.InventoryStockLow.v1'),
  INVENTORY_PO_RECEIVED: schemaNotRegistered('INVENTORY_PO_RECEIVED', 'payload.InventoryPoReceived.v1'),
  INVENTORY_SO_FULFILLED: schemaNotRegistered('INVENTORY_SO_FULFILLED', 'payload.InventorySoFulfilled.v1'),
  INVENTORY_RMA_CREATED: schemaNotRegistered('INVENTORY_RMA_CREATED', 'payload.InventoryRmaCreated.v1'),
  INVENTORY_SALES_ORDER_CREATED: pendingMigration('INVENTORY_SALES_ORDER_CREATED', 'remaining'),
  INVENTORY_SALES_ORDER_UPDATED: pendingMigration('INVENTORY_SALES_ORDER_UPDATED', 'remaining'),
  INVENTORY_SALES_ORDER_DELETED: pendingMigration('INVENTORY_SALES_ORDER_DELETED', 'remaining'),
  INVENTORY_PURCHASE_ORDER_CREATED: pendingMigration('INVENTORY_PURCHASE_ORDER_CREATED', 'remaining'),
  INVENTORY_PURCHASE_ORDER_UPDATED: pendingMigration('INVENTORY_PURCHASE_ORDER_UPDATED', 'remaining'),
  INVENTORY_PURCHASE_ORDER_DELETED: pendingMigration('INVENTORY_PURCHASE_ORDER_DELETED', 'remaining'),
  INVENTORY_TRANSFER_DISPATCHED: pendingMigration('INVENTORY_TRANSFER_DISPATCHED', 'remaining'),
  INVENTORY_TRANSFER_RECEIVED: pendingMigration('INVENTORY_TRANSFER_RECEIVED', 'remaining'),
  INVENTORY_COUNT_SUBMITTED: pendingMigration('INVENTORY_COUNT_SUBMITTED', 'remaining'),
  INVENTORY_COUNT_APPROVED: pendingMigration('INVENTORY_COUNT_APPROVED', 'remaining'),
};
