apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-vnc-test
  namespace: vnc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-vnc-test
  template:
    metadata:
      labels:
        app: ai-vnc-test
    spec:
      containers:
      - name: ai-automation
        image: ghcr.io/nine-minds/alga-psa/ai-automation:vnc-test
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "=== Starting VNC Test in Kubernetes ==="
            echo "Container started at: $(date)"
            echo "Memory limit: $(cat /sys/fs/cgroup/memory/memory.limit_in_bytes 2>/dev/null || echo 'Not set')"
            echo ""
            
            # Use the improved startup script
            if [ -f "./vnc-startup-improved.sh" ]; then
              echo "Using improved VNC startup script..."
              ./vnc-startup-improved.sh
            else
              echo "Using standard VNC startup script..."
              ./vnc-startup.sh
            fi
        env:
        - name: VNC_ENABLED
          value: "true"
        - name: NODE_ENV
          value: "development"
        - name: DISPLAY
          value: ":99"
        - name: XVFB_WHD
          value: "1280x1024x16"
        - name: XVFB_ARGS
          value: "-ac -nolisten tcp -dpi 96 +extension RANDR"
        ports:
        - containerPort: 4000
          name: api
        - containerPort: 5900
          name: vnc
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 256Mi
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ai-vnc-test
  namespace: vnc-test
spec:
  selector:
    app: ai-vnc-test
  ports:
  - name: api
    port: 4000
    targetPort: 4000
  - name: vnc
    port: 5900
    targetPort: 5900
  type: NodePort