apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-vnc-final-verified
  namespace: vnc-final-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-vnc-final-verified
  template:
    metadata:
      labels:
        app: ai-vnc-final-verified
    spec:
      containers:
      - name: ai-automation
        image: harbor.nineminds.com/library/ai-automation:vnc-final-test-amd64
        imagePullPolicy: Always
        env:
        - name: VNC_ENABLED
          value: "true"
        - name: NODE_ENV
          value: "development"
        - name: DISPLAY
          value: ":99"
        - name: PORT
          value: "4000"
        ports:
        - containerPort: 4000
          name: api
        - containerPort: 5900
          name: vnc
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - pgrep -f "Xvfb :99" && pgrep -f "x11vnc" && pgrep -f "websockify"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 3
      imagePullSecrets:
      - name: harbor-credentials
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ai-vnc-final-verified
  namespace: vnc-final-test
spec:
  selector:
    app: ai-vnc-final-verified
  ports:
  - name: api
    port: 4000
    targetPort: 4000
    nodePort: 31400
  - name: vnc
    port: 5900
    targetPort: 5900
    nodePort: 31591
  type: NodePort