version: '3.8'

services:
  pgbouncer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
    secrets:
      - postgres_password
      - db_password_server
    networks:
      - app-network