/**
 * Light and dark theme token values as JS objects.
 * These mirror the CSS custom properties defined in tokens.css and are used
 * by `useTheme().setMode()` to apply inline styles so that theme switching
 * works even when tokens.css isn't loaded or host-provided inline styles
 * would otherwise override the CSS rules.
 */

export const lightTokens: Record<string, string> = {
  '--alga-bg': '#ffffff',
  '--alga-fg': '#0f172a',
  '--alga-muted': '#f5f5f7',
  '--alga-muted-fg': '#4b5563',
  '--alga-primary': '#8a4dea',
  '--alga-primary-foreground': '#ffffff',
  '--alga-primary-light': '#dcc5fb',
  '--alga-primary-dark': '#7c45d3',
  '--alga-primary-50': '#f6f0fe',
  '--alga-primary-100': '#ede2fd',
  '--alga-secondary': '#40cff9',
  '--alga-secondary-foreground': '#ffffff',
  '--alga-secondary-light': '#66dffb',
  '--alga-border': '#e2e8f0',
  '--alga-border-light': '#f1f5f9',
  '--alga-ring': '0 0% 0%',
  '--alga-radius': '8px',
  '--alga-accent': '#ff9c30',
  '--alga-accent-foreground': '#ffffff',
  '--alga-primary-soft': '#f6f0fe',
  '--alga-primary-soft-fg': '#6e3dbb',
  '--alga-primary-soft-hover': '#ede2fd',
  '--alga-primary-border': '#caa8f9',
  '--alga-danger': '#dc2626',
  '--alga-danger-dark': '#b91c1c',
  '--alga-warning': '#f59e0b',
  '--alga-success': '#22c55e',
  '--alga-card-bg': '#f8fafc',
  '--alga-row-even': '#f9fafb',
  '--alga-row-odd': '#ffffff',
  '--alga-row-hover': '#f6f0fe',
};

export const darkTokens: Record<string, string> = {
  '--alga-bg': '#0c0a18',
  '--alga-fg': '#e8e4f6',
  '--alga-muted': '#1b1530',
  '--alga-muted-fg': '#9a92b8',
  '--alga-primary': '#8a4dea',
  '--alga-primary-foreground': '#ffffff',
  '--alga-primary-light': '#472a81',
  '--alga-primary-dark': '#a366f0',
  '--alga-primary-50': '#221743',
  '--alga-primary-100': '#31205c',
  '--alga-secondary': '#40cff9',
  '--alga-secondary-foreground': '#ffffff',
  '--alga-secondary-light': '#66dffb',
  '--alga-border': '#272041',
  '--alga-border-light': '#221743',
  '--alga-ring': '0 0% 98%',
  '--alga-radius': '8px',
  '--alga-accent': '#ffa645',
  '--alga-accent-foreground': '#ffffff',
  '--alga-primary-soft': '#221743',
  '--alga-primary-soft-fg': '#b589f6',
  '--alga-primary-soft-hover': '#31205c',
  '--alga-primary-border': '#5f35a8',
  '--alga-danger': '#ef4444',
  '--alga-danger-dark': '#dc2626',
  '--alga-warning': '#f59e0b',
  '--alga-success': '#10b981',
  '--alga-card-bg': '#1e1836',
  '--alga-row-even': '#1b1530',
  '--alga-row-odd': '#1e1836',
  '--alga-row-hover': '#221743',
};
