import { defineConfig } from 'vitest/config';
import base from './vitest.config';

// Fast behavior checks use activity/transport doubles and need no live Temporal
// environment. The remainder of the Temporal suite requires separate lanes.
export default defineConfig({
  ...base,
  test: {
    ...base.test,
    include: [
      'src/__tests__/marketing-worker-registration.test.ts',
      'src/__tests__/worker-registration.test.ts',
      'src/activities/__tests__/portalDomainActivitiesTenantScoped.contract.test.ts',
      'src/activities/__tests__/slaActivitiesTenantScoped.contract.test.ts',
      'src/workflows/__tests__/kb-article-import-wiring.contract.test.ts',
      'src/workflows/__tests__/tenant-creation-product-bootstrap.contract.test.ts',
      'src/workflows/__tests__/tenant-email-ingestion-workflow.contract.test.ts',
      'src/workflows/__tests__/tenant-suspension-workflow.contract.test.ts',

      'src/__tests__/worker-queue-ownership.test.ts',
      'src/__tests__/temporal-worker-shared-tenant-secrets.helm.test.ts',
      'src/config/__tests__/**/*.test.ts',
      'src/workflows/__tests__/generic-job-workflow.temporal.test.ts',
      'src/workflows/__tests__/workflow-runtime-v2-interpreter.test.ts',
      'src/workflows/__tests__/workflow-runtime-v2-run-workflow.test.ts',
      'src/workflows/__tests__/workflow-runtime-v2-simulator-contract.test.ts',
      'src/activities/__tests__/workflow-runtime-v2-activities.test.ts',
      'src/activities/__tests__/sla-activities.test.ts',
      'src/activities/__tests__/marketing-activities.test.ts',
      'src/activities/__tests__/tenant-suspension-activities.test.ts',
      'src/activities/__tests__/tenant-email-ingestion-activities.test.ts',
      'src/db/__tests__/tenant-operations.email-settings.test.ts',
      'src/activities/__tests__/product-upgrade-activities.test.ts',
      'src/activities/__tests__/trial-payment-reminder-activities.test.ts',
      'src/activities/__tests__/trial-payment-reminder-email.test.ts',
      'src/activities/__tests__/comment-recovery-forwarding.test.ts',
      'src/activities/__tests__/customer-tracking-activities.test.ts',
      'src/activities/__tests__/email-activities-portal-status.test.ts',
      'src/activities/__tests__/portal-user-operations.test.ts',
      'src/activities/__tests__/email-activities-simple.test.ts',
      'src/activities/__tests__/email-activities-standalone.test.ts',
      'src/activities/__tests__/email-activities.temporal.test.ts',
      'src/activities/__tests__/gmail-adapter-secret-log-hygiene.test.ts',
      'src/activities/__tests__/microsoft-email-filesystem-secret-provider.test.ts',
      'src/activities/__tests__/portal-domain-activities.test.ts',
      'src/activities/__tests__/portal-domain-reconcile.integration.test.ts',
      'src/activities/__tests__/portal-domain-activities.git.test.ts',
      'src/activities/__tests__/portal-domain-nextauth-url.test.ts',
      'src/workflows/__tests__/marketing-fanout-workflow.test.ts',
      'src/workflows/__tests__/ninjaone-token-refresh-workflow.test.ts',
      'src/workflows/__tests__/tenant-deletion-workflow.behavior.test.ts',
      'src/db/__tests__/product-bootstrap-resolver.test.ts',
      'src/db/__tests__/permission-catalog-packaging.test.ts',
      'src/db/__tests__/product-upgrade-role-grants.contract.test.ts',
      'src/schedules/__tests__/**/*.test.ts',
      'src/scripts/__tests__/upgrade-tenant-product.test.ts',
    ],
    coverage: { provider: 'v8', enabled: false },
    fileParallelism: false,
    maxWorkers: 1,
  },
});
