{{- if .Values.redis.enabled }}
{{- $ns := include "sebastian.namespace" . -}}
{{- $existing := (lookup "v1" "Secret" $ns "redis-credentials") -}}
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: {{ include "sebastian.namespace" . }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- if $existing }}
  REDIS_PASSWORD: {{ index $existing.data "REDIS_PASSWORD" }}
{{- else if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
{{- else }}
  REDIS_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- end }}
