apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - platform/appliance-status.yaml
  - releases/alga-core.yaml
  - releases/pgbouncer.yaml
  - releases/temporal.yaml
  - releases/workflow-worker.yaml
  - releases/email-service.yaml
  - releases/temporal-worker.yaml
