export const WORKFLOW_REGEX_TRANSFORM_GUIDANCE = [
  'Workflow regex transform authoring guidance:',
  '- Use action.call with transform.regex_match to evaluate a pattern and return { matched, match, index, groups, namedGroups }.',
  '- Use action.call with transform.regex_extract to gather multiple matches and return { matched, count, first, matches }.',
  '- Use action.call with transform.regex_replace to normalize text and return { text, replacementCount }.',
  '- Enter JavaScript RegExp pattern bodies without surrounding slashes (for example pattern: "INC-(\\\\d{6})").',
  '- Supported JavaScript regex flags are d, g, i, m, s, u, v, y. Duplicate or unsupported flags fail fast.',
  '- For transform.regex_extract and transform.regex_match, requireMatch: true converts no-match into an explicit action failure.',
  '- For transform.regex_extract, set maxMatches to keep results bounded and deterministic.',
  '- For transform.regex_replace, JavaScript replacement tokens are supported, including $1, $2, $<name>, and $$.',
  '- Save outputs with action.call.saveAs (for example saveAs: vars.parsedAlert or saveAs: payload.normalizedText).',
  '- Example incident extraction: pattern "INC-(?<incidentId>\\\\d{6})", then reference vars.parsedIncident.first.namedGroups.incidentId.',
  '- Example hostname + serial extraction: pattern "host\\\\s+(?<host>[a-z0-9-]+)\\\\s+serial\\\\s+(?<serial>SN-\\\\d+)".',
  '- Example whitespace normalization: pattern "\\\\s+", replacement " ", replaceAll: true.',
  '- Example asset tag extraction: pattern "(?<assetTag>AST-[A-Z0-9]{5,10})".',
  '- Regex guardrails enforce max text length, max pattern length, and max match count; advise users to keep patterns targeted.',
  '- If regex captures include sensitive or secret-derived text, saveAs may persist it to payload/vars/meta; only save what is intended for downstream access.',
  '- AI only helps author deterministic workflow configuration; workflow runtime executes transform.regex_* actions without AI inference.',
].join('\n');
