import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'index.ts',
    'types/index': 'types/index.ts',
    'core/index': 'core/index.ts',
    'core/logger': 'core/logger.ts',
    'core/secretProvider': 'core/secretProvider.ts',
    'db/index': 'db/index.ts',
    'db/admin': 'db/admin.ts',
    'db/connection': 'db/connection.ts',
    'db/tenant': 'db/tenant.ts',
    'events/publisher': 'events/publisher.ts',
    'utils/encryption': 'utils/encryption.ts',
    'utils/retryUtils': 'utils/retryUtils.ts',
    'workflow/index': 'workflow/index.ts',
    'workflow/core/index': 'workflow/core/index.ts',
    'workflow/runtime/index': 'workflow/runtime/index.ts',
    'workflow/persistence/index': 'workflow/persistence/index.ts',
    'workflow/persistence/workflowEventProcessingModel': 'workflow/persistence/workflowEventProcessingModel.ts',
    'workflow/streams/index': 'workflow/streams/index.ts',
    'workflow/streams/redisStreamClient': 'workflow/streams/redisStreamClient.ts',
    'workflow/workers/index': 'workflow/workers/index.ts',
    'workflow/init/index': 'workflow/init/index.ts',
    'workflow/services/index': 'workflow/services/index.ts',
    'extension-utils/index': 'extension-utils/index.ts',
    'models/clientModel': 'models/clientModel.ts',
    'models/contactModel': 'models/contactModel.ts',
    'models/tagModel': 'models/tagModel.ts',
    'models/ticketModel': 'models/ticketModel.ts',
    'models/userModel': 'models/userModel.ts',
    'extensions/domain': 'extensions/domain.ts',
    'extensions/installs': 'extensions/installs.ts',
    'extensions/types': 'extensions/types.ts',
    'billingClients/index': 'billingClients/index.ts',
  },
  format: ['esm'],
  dts: false,
  bundle: true,
  splitting: true,
  sourcemap: false,
  clean: true,
  outDir: 'dist',
  external: [
    'react',
    'react-dom',
    'knex',
    'pg',
    'redis',
    'winston',
    'winston-daily-rotate-file',
    'uuid',
    'zod',
    'dotenv',
    'axios',
    'jsonata',
    'turndown',
    'node-vault',
    'googleapis',
    'google-auth-library',
    '@js-temporal/polyfill',
    /^@alga-psa\//,
  ],
  noExternal: [
    /^@shared\//,
  ],
});
