const BATCH_SIZE = 1000;

/**
 * Backfill one top-level thread per existing comment on both surfaces.
 *
 * Legacy thread_id is set to the comment_id for deterministic, idempotent
 * reruns and to avoid maintaining a temporary mapping table. Future writes
 * use generated thread IDs.
 *
 * @param {import('knex').Knex} knex
 * @returns {Promise<void>}
 */
exports.up = async function up(knex) {
  await backfillTicketComments(knex);
  await backfillProjectTaskComments(knex);
};

async function backfillTicketComments(knex) {
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const result = await knex.raw(
      `
        WITH batch AS (
          SELECT
            tenant,
            comment_id,
            ticket_id,
            is_internal,
            created_at,
            user_id,
            metadata
          FROM comments
          WHERE thread_id IS NULL
          ORDER BY created_at, comment_id
          LIMIT ?
        ),
        inserted AS (
          INSERT INTO comment_threads (
            tenant,
            thread_id,
            ticket_id,
            project_task_id,
            root_comment_id,
            is_internal,
            reply_count,
            last_activity_at,
            email_message_id,
            created_at,
            created_by
          )
          SELECT
            tenant,
            comment_id,
            ticket_id,
            NULL,
            comment_id,
            is_internal,
            0,
            COALESCE(created_at, now()),
            metadata->'email'->>'messageId',
            COALESCE(created_at, now()),
            user_id
          FROM batch
          ON CONFLICT (tenant, thread_id) DO NOTHING
        )
        UPDATE comments c
        SET thread_id = b.comment_id
        FROM batch b
        WHERE c.tenant = b.tenant
          AND c.comment_id = b.comment_id
          AND c.thread_id IS NULL
        RETURNING c.comment_id
      `,
      [BATCH_SIZE]
    );

    if ((result.rowCount ?? result.rows?.length ?? 0) === 0) {
      break;
    }
  }
}

async function backfillProjectTaskComments(knex) {
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const result = await knex.raw(
      `
        WITH batch AS (
          SELECT
            tenant,
            task_comment_id,
            task_id,
            created_at,
            user_id
          FROM project_task_comments
          WHERE thread_id IS NULL
          ORDER BY created_at, task_comment_id
          LIMIT ?
        ),
        inserted AS (
          INSERT INTO comment_threads (
            tenant,
            thread_id,
            ticket_id,
            project_task_id,
            root_comment_id,
            is_internal,
            reply_count,
            last_activity_at,
            created_at,
            created_by
          )
          SELECT
            tenant,
            task_comment_id,
            NULL,
            task_id,
            task_comment_id,
            false,
            0,
            COALESCE(created_at, now()),
            COALESCE(created_at, now()),
            user_id
          FROM batch
          ON CONFLICT (tenant, thread_id) DO NOTHING
        )
        UPDATE project_task_comments c
        SET thread_id = b.task_comment_id
        FROM batch b
        WHERE c.tenant = b.tenant
          AND c.task_comment_id = b.task_comment_id
          AND c.thread_id IS NULL
        RETURNING c.task_comment_id
      `,
      [BATCH_SIZE]
    );

    if ((result.rowCount ?? result.rows?.length ?? 0) === 0) {
      break;
    }
  }
}

/**
 * Reverse the backfill: clear thread_id for legacy rows (where thread_id was
 * derived from the comment_id) and drop their thread rows.
 *
 * Comments whose thread_id was generated by the application layer (i.e. not
 * equal to comment_id, or which already have a parent) are left intact because
 * they predate / outlive this migration.
 *
 * @param {import('knex').Knex} knex
 * @returns {Promise<void>}
 */
exports.down = async function down(knex) {
  await knex.raw(`
    UPDATE comments
    SET thread_id = NULL
    WHERE thread_id = comment_id
      AND parent_comment_id IS NULL
  `);

  await knex.raw(`
    UPDATE project_task_comments
    SET thread_id = NULL
    WHERE thread_id = task_comment_id
      AND parent_comment_id IS NULL
  `);

  await knex.raw(`
    DELETE FROM comment_threads ct
    WHERE ct.thread_id = ct.root_comment_id
      AND (
        (ct.project_task_id IS NULL AND NOT EXISTS (
          SELECT 1 FROM comments c
          WHERE c.tenant = ct.tenant AND c.thread_id = ct.thread_id
        ))
        OR
        (ct.ticket_id IS NULL AND NOT EXISTS (
          SELECT 1 FROM project_task_comments c
          WHERE c.tenant = ct.tenant AND c.thread_id = ct.thread_id
        ))
      )
  `);
};

// Chunked backfill commits each batch independently; it must not run inside
// a wrapping transaction.
exports.config = { transaction: false };
