// Backfill one top-level thread per existing comment. Two single-table
// statements per surface (INSERT ... ON CONFLICT, then UPDATE ... FROM):
// Citus does not reliably run multi-table WITH...INSERT...UPDATE across two
// distributed tables. Legacy thread_id = comment_id for idempotent reruns.
exports.up = async function up(knex) {
  await backfillTicketComments(knex);
  await backfillProjectTaskComments(knex);
};

async function backfillTicketComments(knex) {
  const { rows } = await knex.raw(
    'SELECT EXISTS (SELECT 1 FROM comments WHERE thread_id IS NULL) AS has_gap'
  );
  if (!rows?.[0]?.has_gap) {
    return;
  }

  await knex.raw(`
    INSERT INTO comment_threads (
      tenant,
      thread_id,
      ticket_id,
      project_task_id,
      root_comment_id,
      is_internal,
      reply_count,
      last_activity_at,
      email_message_id,
      created_at,
      created_by
    )
    SELECT
      tenant,
      comment_id,
      ticket_id,
      NULL,
      comment_id,
      is_internal,
      0,
      COALESCE(created_at, now()),
      metadata->'email'->>'messageId',
      COALESCE(created_at, now()),
      user_id
    FROM comments
    WHERE thread_id IS NULL
    ON CONFLICT (tenant, thread_id) DO NOTHING
  `);

  // UPDATE ... FROM on the co-located tenant column: Citus's reliable
  // cross-table write (correlated EXISTS in UPDATE is inconsistently
  // supported). Only touches rows whose thread row now exists.
  await knex.raw(`
    UPDATE comments c
    SET thread_id = ct.thread_id
    FROM comment_threads ct
    WHERE c.tenant = ct.tenant
      AND ct.thread_id = c.comment_id
      AND c.thread_id IS NULL
  `);
}

async function backfillProjectTaskComments(knex) {
  const { rows } = await knex.raw(
    'SELECT EXISTS (SELECT 1 FROM project_task_comments WHERE thread_id IS NULL) AS has_gap'
  );
  if (!rows?.[0]?.has_gap) {
    return;
  }

  await knex.raw(`
    INSERT INTO comment_threads (
      tenant,
      thread_id,
      ticket_id,
      project_task_id,
      root_comment_id,
      is_internal,
      reply_count,
      last_activity_at,
      created_at,
      created_by
    )
    SELECT
      tenant,
      task_comment_id,
      NULL,
      task_id,
      task_comment_id,
      false,
      0,
      COALESCE(created_at, now()),
      COALESCE(created_at, now()),
      user_id
    FROM project_task_comments
    WHERE thread_id IS NULL
    ON CONFLICT (tenant, thread_id) DO NOTHING
  `);

  await knex.raw(`
    UPDATE project_task_comments c
    SET thread_id = ct.thread_id
    FROM comment_threads ct
    WHERE c.tenant = ct.tenant
      AND ct.thread_id = c.task_comment_id
      AND c.thread_id IS NULL
  `);
}

/**
 * Reverse the backfill: clear thread_id for legacy rows (where thread_id was
 * derived from the comment_id) and drop their thread rows.
 *
 * Comments whose thread_id was generated by the application layer (i.e. not
 * equal to comment_id, or which already have a parent) are left intact because
 * they predate / outlive this migration.
 *
 * @param {import('knex').Knex} knex
 * @returns {Promise<void>}
 */
exports.down = async function down(knex) {
  await knex.raw(`
    UPDATE comments
    SET thread_id = NULL
    WHERE thread_id = comment_id
      AND parent_comment_id IS NULL
  `);

  await knex.raw(`
    UPDATE project_task_comments
    SET thread_id = NULL
    WHERE thread_id = task_comment_id
      AND parent_comment_id IS NULL
  `);

  await knex.raw(`
    DELETE FROM comment_threads ct
    WHERE ct.thread_id = ct.root_comment_id
      AND (
        (ct.project_task_id IS NULL AND NOT EXISTS (
          SELECT 1 FROM comments c
          WHERE c.tenant = ct.tenant AND c.thread_id = ct.thread_id
        ))
        OR
        (ct.ticket_id IS NULL AND NOT EXISTS (
          SELECT 1 FROM project_task_comments c
          WHERE c.tenant = ct.tenant AND c.thread_id = ct.thread_id
        ))
      )
  `);
};

// Backfill issues single-table statements that Citus routes per shard; both
// operations must commit independently and stay outside a wrapping txn so a
// partial failure doesn't undo rows already populated.
exports.config = { transaction: false };
