apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alga-core
  namespace: alga-system
spec:
  interval: 10m
  timeout: 30m
  releaseName: alga-core
  targetNamespace: msp
  install:
    createNamespace: true
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  chart:
    spec:
      chart: sebastian
      version: 0.0.1
      interval: 10m
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: alga-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: appliance-values-alga-core
      valuesKey: alga-core.single-node.yaml
