apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: email-service
  namespace: alga-system
spec:
  interval: 10m
  timeout: 30m
  dependsOn:
    - name: alga-core
    - name: pgbouncer
  releaseName: email-service
  targetNamespace: msp
  install:
    createNamespace: true
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  chart:
    spec:
      chart: email-service
      version: 0.1.0
      interval: 10m
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: alga-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: appliance-values-email-service
      valuesKey: email-service.single-node.yaml
