import { ApiOpenApiRegistry, zOpenApi } from '../registry';

export function registerAutomationRoutes(registry: ApiOpenApiRegistry) {
  const tag = 'Automation';

  const ExecutionStatus = zOpenApi.enum(['pending', 'running', 'completed', 'failed', 'cancelled', 'timeout', 'skipped']);
  const TriggerType = zOpenApi.enum(['time_based', 'event_based', 'condition_based', 'manual', 'recurring', 'webhook']);
  const ActionType = zOpenApi.enum([
    'email_notification',
    'sms_notification',
    'webhook_call',
    'database_update',
    'ticket_creation',
    'ticket_update',
    'project_update',
    'time_entry_creation',
    'invoice_generation',
    'custom_script',
    'workflow_execution',
    'system_command',
  ]);

  const AutomationExecutionParams = registry.registerSchema(
    'AutomationExecutionParams',
    zOpenApi.object({
      id: zOpenApi.string().uuid().describe('Automation execution UUID from automation_executions.execution_id.'),
    }),
  );

  const AutomationExecutionsListQuery = registry.registerSchema(
    'AutomationExecutionsListQuery',
    zOpenApi.object({
      page: zOpenApi.string().optional().describe('Page number as a query string. Defaults to 1.'),
      limit: zOpenApi.string().optional().describe('Page size as a query string. Must parse to 1 through 100; defaults to 25.'),
      sort: zOpenApi.string().optional().describe('Accepted by shared list query validation; the service currently orders executions by started_at desc.'),
      order: zOpenApi.enum(['asc', 'desc']).optional().describe('Accepted by shared list query validation.'),
      search: zOpenApi.string().optional().describe('Accepted by shared filter validation.'),
      created_from: zOpenApi.string().datetime().optional().describe('Accepted by shared filter validation.'),
      created_to: zOpenApi.string().datetime().optional().describe('Accepted by shared filter validation.'),
      updated_from: zOpenApi.string().datetime().optional().describe('Accepted by shared filter validation.'),
      updated_to: zOpenApi.string().datetime().optional().describe('Accepted by shared filter validation.'),
      is_active: zOpenApi.enum(['true', 'false']).optional().describe('Accepted by shared filter validation and transformed to boolean.'),
      automation_rule_id: zOpenApi.string().uuid().optional().describe('Filter executions by parent automation rule UUID.'),
      status: ExecutionStatus.optional().describe('Filter by execution status.'),
      started_from: zOpenApi.string().datetime().optional().describe('Filter executions started at or after this timestamp.'),
      started_to: zOpenApi.string().datetime().optional().describe('Filter executions started at or before this timestamp.'),
      duration_min_ms: zOpenApi.number().min(0).optional().describe('Minimum execution duration in milliseconds.'),
      duration_max_ms: zOpenApi.number().min(0).optional().describe('Maximum execution duration in milliseconds.'),
      has_errors: zOpenApi.enum(['true', 'false']).optional().describe('Filter by whether the execution has errors; transformed to boolean by validation.'),
      trigger_type: TriggerType.optional().describe('Filter by automation trigger type.'),
    }),
  );

  const AutomationLogEntry = registry.registerSchema(
    'AutomationExecutionLogEntry',
    zOpenApi.object({
      timestamp: zOpenApi.string().datetime().optional().describe('Log timestamp.'),
      level: zOpenApi.enum(['debug', 'info', 'warn', 'error']).describe('Log level.'),
      message: zOpenApi.string().describe('Log message.'),
      action_index: zOpenApi.number().int().optional().describe('Optional action index that produced the log.'),
      metadata: zOpenApi.record(zOpenApi.unknown()).optional().describe('Optional structured log metadata.'),
    }),
  );

  const AutomationLinks = registry.registerSchema(
    'AutomationLinks',
    zOpenApi.record(zOpenApi.unknown()).describe('HATEOAS links generated by the automation controller. Some generic links may point to methods not implemented by a route file.'),
  );

  const AutomationExecution = registry.registerSchema(
    'AutomationExecution',
    zOpenApi.object({
      execution_id: zOpenApi.string().uuid().describe('Execution UUID generated with crypto.randomUUID when the execution is created.'),
      automation_rule_id: zOpenApi.string().uuid().describe('Parent automation rule UUID.'),
      trigger_data: zOpenApi.record(zOpenApi.unknown()).optional().describe('Trigger payload captured when execution started.'),
      status: ExecutionStatus.describe('Current execution status.'),
      started_at: zOpenApi.string().datetime().optional().describe('Timestamp when execution started.'),
      completed_at: zOpenApi.string().datetime().nullable().optional().describe('Timestamp when execution completed.'),
      duration_ms: zOpenApi.number().min(0).nullable().optional().describe('Execution duration in milliseconds.'),
      actions_total: zOpenApi.number().int().min(0).describe('Number of actions planned for this execution.'),
      actions_successful: zOpenApi.number().int().min(0).describe('Number of actions completed successfully.'),
      actions_failed: zOpenApi.number().int().min(0).describe('Number of actions that failed.'),
      error_message: zOpenApi.string().nullable().optional().describe('Top-level error message, when failed.'),
      error_stack: zOpenApi.string().nullable().optional().describe('Error stack, when captured.'),
      failed_action_index: zOpenApi.number().int().nullable().optional().describe('Index of failed action, when applicable.'),
      execution_context: zOpenApi.record(zOpenApi.unknown()).optional().describe('Execution context data.'),
      logs: zOpenApi.array(AutomationLogEntry).optional().describe('Execution log entries.'),
      tenant: zOpenApi.string().uuid().describe('Tenant UUID scoped from the API key context.'),
      _links: AutomationLinks.optional(),
    }),
  );

  const AutomationPagination = registry.registerSchema(
    'AutomationPagination',
    zOpenApi.object({
      page: zOpenApi.number().int().describe('Current page number.'),
      limit: zOpenApi.number().int().describe('Page size.'),
      total: zOpenApi.number().int().describe('Total matching executions.'),
      totalPages: zOpenApi.number().int().describe('Total page count.'),
      hasNext: zOpenApi.boolean().describe('Whether another page exists.'),
      hasPrev: zOpenApi.boolean().describe('Whether a previous page exists.'),
    }),
  );

  const AutomationExecutionListResponse = registry.registerSchema(
    'AutomationExecutionListResponse',
    zOpenApi.object({
      data: zOpenApi.array(AutomationExecution).describe('Automation execution rows. Current service code wraps the DB result array in another array; this schema documents the intended flat shape returned by createPaginatedResponse.'),
      pagination: AutomationPagination,
      meta: zOpenApi.object({
        filters: zOpenApi.record(zOpenApi.unknown()).optional().describe('Validated filters echoed by the controller.'),
        resource: zOpenApi.literal('automation_execution').optional().describe('Resource name supplied by the controller.'),
      }).optional(),
    }),
  );

  const AutomationExecutionResponse = registry.registerSchema(
    'AutomationExecutionResponse',
    zOpenApi.object({
      data: AutomationExecution,
    }),
  );

  const AutomationErrorResponse = registry.registerSchema(
    'AutomationErrorResponse',
    zOpenApi.object({
      error: zOpenApi.object({
        code: zOpenApi.string().describe('Machine-readable error code, such as UNAUTHORIZED, FORBIDDEN, VALIDATION_ERROR, or INTERNAL_ERROR.'),
        message: zOpenApi.string().describe('Human-readable error message.'),
        details: zOpenApi.unknown().optional().describe('Optional structured error details.'),
      }),
    }),
  );

  const AutomationMetaResponse = registry.registerSchema(
    'AutomationMetaResponse',
    zOpenApi.object({
      data: zOpenApi.object({
        trigger_types: zOpenApi.array(TriggerType).describe('Valid automation trigger types.'),
        action_types: zOpenApi.array(ActionType).describe('Valid automation action types.'),
        rule_statuses: zOpenApi.array(zOpenApi.enum(['active', 'inactive', 'draft', 'error'])).describe('Valid automation rule statuses.'),
        execution_statuses: zOpenApi.array(ExecutionStatus).describe('Valid automation execution statuses.'),
        priority_levels: zOpenApi.array(zOpenApi.enum(['low', 'normal', 'high', 'critical'])).describe('Valid automation priority levels.'),
        condition_operators: zOpenApi.array(zOpenApi.enum([
          'equals',
          'not_equals',
          'greater_than',
          'less_than',
          'greater_than_or_equal',
          'less_than_or_equal',
          'contains',
          'not_contains',
          'starts_with',
          'ends_with',
          'in',
          'not_in',
          'exists',
          'not_exists',
          'regex_match',
        ])).describe('Valid condition operators.'),
      }),
    }),
  );

  registry.registerRoute({
    method: 'get',
    path: '/api/v1/automation/executions',
    summary: 'List automation executions',
    description:
      'Returns a paginated list of automation executions for the authenticated tenant. Authentication uses x-api-key with optional x-tenant-id; the controller validates the API key, resolves the user and tenant, runs under tenant context, and requires automation:read permission. The service forces tenant into the execution query conditions. Current service code appears to wrap the execution array in another array before createPaginatedResponse, which may produce nested data in practice.',
    tags: [tag],
    security: [{ ApiKeyAuth: [] }],
    request: { query: AutomationExecutionsListQuery },
    responses: {
      200: { description: 'Automation executions returned successfully.', schema: AutomationExecutionListResponse },
      400: { description: 'Query parameter validation failed.', schema: AutomationErrorResponse },
      401: { description: 'API key is missing, invalid, expired, over limit, or the key user was not found.', schema: AutomationErrorResponse },
      403: { description: 'Authenticated user lacks automation:read permission.', schema: AutomationErrorResponse },
      500: { description: 'Unexpected automation execution listing failure.', schema: AutomationErrorResponse },
    },
    extensions: {
      'x-tenant-scoped': true,
      'x-rbac-resource': 'automation',
      'x-rbac-action': 'read',
      'x-service-data-wrapping-bug': true,
    },
    edition: 'both',
  });

  registry.registerRoute({
    method: 'get',
    path: '/api/v1/automation/executions/{id}',
    summary: 'Get automation execution',
    description:
      'Returns one automation execution by execution_id for the authenticated tenant, with HATEOAS links to the parent rule and retry endpoint when the status is failed. Authentication uses x-api-key with optional x-tenant-id; the controller validates the API key, resolves tenant context, validates the UUID path parameter, and requires automation:read permission. The service scopes lookup by execution_id and tenant. Missing executions currently throw a generic Error and may surface as 500 rather than 404.',
    tags: [tag],
    security: [{ ApiKeyAuth: [] }],
    request: { params: AutomationExecutionParams },
    responses: {
      200: { description: 'Automation execution returned successfully.', schema: AutomationExecutionResponse },
      400: { description: 'Invalid execution UUID format.', schema: AutomationErrorResponse },
      401: { description: 'API key is missing, invalid, expired, over limit, or the key user was not found.', schema: AutomationErrorResponse },
      403: { description: 'Authenticated user lacks automation:read permission.', schema: AutomationErrorResponse },
      404: { description: 'Intended not-found response for a missing execution; current service may surface this as 500.', schema: AutomationErrorResponse },
      500: { description: 'Unexpected failure, including current generic not-found errors.', schema: AutomationErrorResponse },
    },
    extensions: {
      'x-tenant-scoped': true,
      'x-rbac-resource': 'automation',
      'x-rbac-action': 'read',
      'x-no-clean-not-found-currently': true,
      'x-generic-resource-links-may-include-unimplemented-methods': true,
    },
    edition: 'both',
  });

  registry.registerRoute({
    method: 'post',
    path: '/api/v1/automation/executions/{id}/retry',
    summary: 'Retry automation execution',
    description:
      'Retries a failed automation execution. The controller authenticates with x-api-key, requires automation:execute permission, validates the execution UUID, resets a failed execution to pending, clears completion/error counters, queues the execution, publishes automation.execution.retried, and returns the updated execution with links. The service only allows status=failed; missing executions and non-failed executions currently throw generic Errors and may surface as 500 rather than 404 or 400. The queueExecution helper is currently a stub.',
    tags: [tag],
    security: [{ ApiKeyAuth: [] }],
    request: { params: AutomationExecutionParams },
    responses: {
      200: { description: 'Execution reset and queued for retry.', schema: AutomationExecutionResponse },
      400: { description: 'Invalid execution UUID format, or intended response when execution is not failed.', schema: AutomationErrorResponse },
      401: { description: 'API key is missing, invalid, expired, over limit, or the key user was not found.', schema: AutomationErrorResponse },
      403: { description: 'Authenticated user lacks automation:execute permission.', schema: AutomationErrorResponse },
      404: { description: 'Intended not-found response for a missing execution; current service may surface this as 500.', schema: AutomationErrorResponse },
      500: { description: 'Unexpected failure, including current generic not-found or not-failed errors.', schema: AutomationErrorResponse },
    },
    extensions: {
      'x-tenant-scoped': true,
      'x-rbac-resource': 'automation',
      'x-rbac-action': 'execute',
      'x-requires-current-status': 'failed',
      'x-queues-execution-stubbed': true,
      'x-publishes-event': 'automation.execution.retried',
      'x-no-clean-not-found-currently': true,
      'x-not-failed-error-is-500-currently': true,
    },
    edition: 'both',
  });

  registry.registerRoute({
    method: 'get',
    path: '/api/v1/automation/meta',
    summary: 'Get automation metadata',
    description:
      'Returns a static reference catalog of automation enum values: trigger types, action types, rule statuses, execution statuses, priority levels, and condition operators. Authentication uses x-api-key with optional x-tenant-id; the controller validates the API key, resolves tenant context, and requires automation:read permission. The response is hardcoded and performs no service or database lookup beyond authentication/RBAC.',
    tags: [tag],
    security: [{ ApiKeyAuth: [] }],
    responses: {
      200: { description: 'Automation metadata returned successfully.', schema: AutomationMetaResponse },
      401: { description: 'API key is missing, invalid, expired, over limit, or the key user was not found.', schema: AutomationErrorResponse },
      403: { description: 'Authenticated user lacks automation:read permission.', schema: AutomationErrorResponse },
      500: { description: 'Unexpected automation metadata failure.', schema: AutomationErrorResponse },
    },
    extensions: {
      'x-tenant-scoped': true,
      'x-rbac-resource': 'automation',
      'x-rbac-action': 'read',
      'x-static-reference-data': true,
    },
    edition: 'both',
  });
}
