import { ApiOpenApiRegistry, zOpenApi } from '../registry';

export function registerBillingRoutes(registry: ApiOpenApiRegistry) {
  const tag = 'Billing';

  registry.registerComponent('securitySchemes', 'WebhookSignatureAuth', {
    type: 'apiKey',
    in: 'header',
    name: 'x-webhook-signature',
    description:
      'HMAC-SHA256 signature generated with ALGA_WEBHOOK_SECRET. POST signs the raw JSON body. GET signs the string GET:<tenant_id>.',
  });

  const LicenceCountHeaders = registry.registerSchema(
    'LicenceCountHeaders',
    zOpenApi.object({
      'x-webhook-signature': zOpenApi
        .string()
        .describe('HMAC-SHA256 hex digest proving the caller knows ALGA_WEBHOOK_SECRET.'),
    }),
  );

  const LicenceCountQuery = registry.registerSchema(
    'LicenceCountQuery',
    zOpenApi.object({
      tenant_id: zOpenApi
        .string()
        .describe('Tenant identifier to query. This must match a tenants.tenant record.'),
    }),
  );

  const LicenceUsageResponse = registry.registerSchema(
    'LicenceUsageResponse',
    zOpenApi.object({
      tenant_id: zOpenApi.string().describe('Echoed tenant identifier from the request.'),
      limit: zOpenApi
        .number()
        .int()
        .nullable()
        .describe('Licensed internal-user count from tenants.licensed_user_count. Null means unlimited.'),
      used: zOpenApi
        .number()
        .int()
        .describe('Count of active internal users where users.user_type is internal and is_inactive is false.'),
      remaining: zOpenApi
        .number()
        .int()
        .nullable()
        .describe('Calculated remaining seats as max(0, limit - used), or null when limit is unlimited.'),
      last_updated: zOpenApi
        .string()
        .nullable()
        .describe('ISO timestamp from tenants.last_license_update, or null if no license update has been recorded.'),
    }),
  );

  const LicenceCountUpdateRequest = registry.registerSchema(
    'LicenceCountUpdateRequest',
    zOpenApi.object({
      tenant_id: zOpenApi
        .string()
        .describe('Tenant identifier from tenants.tenant whose licensed user count should be updated.'),
      license_count: zOpenApi
        .number()
        .int()
        .min(0)
        .describe('Licensed internal-user count from the Stripe subscription quantity.'),
      event_id: zOpenApi
        .string()
        .optional()
        .describe('Stripe webhook event ID. When supplied, the handler uses tenants.stripe_event_id for idempotency.'),
    }),
  );

  const LicenceCountUpdateResponse = registry.registerSchema(
    'LicenceCountUpdateResponse',
    zOpenApi.object({
      success: zOpenApi.literal(true).describe('Indicates the license count update was accepted.'),
      tenant_id: zOpenApi.string().describe('Echoed tenant identifier that was updated.'),
      license_count: zOpenApi.number().int().describe('Echoed licensed user count that was written.'),
      updated_at: zOpenApi
        .string()
        .datetime()
        .describe('ISO timestamp generated by the handler for this response.'),
    }),
  );

  const LicenceCountErrorResponse = registry.registerSchema(
    'LicenceCountErrorResponse',
    zOpenApi.object({
      error: zOpenApi.string().describe('Human-readable error message.'),
    }),
  );

  registry.registerRoute({
    method: 'get',
    path: '/api/billing/licence-count',
    summary: 'Get tenant licence usage',
    description:
      'Server-to-server webhook endpoint used by the billing service to query current licence usage for a tenant. The caller supplies tenant_id and an x-webhook-signature header containing HMAC-SHA256("GET:<tenant_id>", ALGA_WEBHOOK_SECRET). The response reports the configured licensed internal-user limit, active internal-user count, calculated remaining seats, and last licence update timestamp.',
    tags: [tag],
    security: [{ WebhookSignatureAuth: [] }],
    request: {
      query: LicenceCountQuery,
      headers: LicenceCountHeaders,
    },
    responses: {
      200: {
        description: 'Licence usage returned successfully.',
        schema: LicenceUsageResponse,
      },
      400: {
        description: 'Missing tenant_id query parameter.',
        schema: LicenceCountErrorResponse,
      },
      401: {
        description: 'Webhook signature missing or invalid.',
        schema: LicenceCountErrorResponse,
      },
      404: {
        description: 'Tenant not found.',
        schema: LicenceCountErrorResponse,
      },
      500: {
        description: 'Unexpected internal error.',
        schema: LicenceCountErrorResponse,
      },
    },
    extensions: {
      'x-webhook-secured': true,
      'x-server-to-server': true,
    },
    edition: 'both',
  });

  registry.registerRoute({
    method: 'post',
    path: '/api/billing/licence-count',
    summary: 'Update tenant licensed user count',
    description:
      'Server-to-server webhook endpoint used by the billing service to synchronize a tenant\'s licensed internal-user count from a Stripe subscription quantity. The x-webhook-signature header must be the HMAC-SHA256 hex digest of the raw JSON request body using ALGA_WEBHOOK_SECRET. When event_id is provided, the handler treats tenants.stripe_event_id as an idempotency marker and skips duplicate Stripe events.',
    tags: [tag],
    security: [{ WebhookSignatureAuth: [] }],
    request: {
      headers: LicenceCountHeaders,
      body: {
        schema: LicenceCountUpdateRequest,
        description: 'Licence count update payload from the billing service.',
      },
    },
    responses: {
      200: {
        description: 'Licence count update accepted, or duplicate event safely ignored.',
        schema: LicenceCountUpdateResponse,
      },
      400: {
        description: 'tenant_id or license_count is missing or invalid.',
        schema: LicenceCountErrorResponse,
      },
      401: {
        description: 'Webhook signature missing or invalid.',
        schema: LicenceCountErrorResponse,
      },
      404: {
        description: 'Tenant not found.',
        schema: LicenceCountErrorResponse,
      },
      500: {
        description: 'Unexpected internal error.',
        schema: LicenceCountErrorResponse,
      },
    },
    extensions: {
      'x-webhook-secured': true,
      'x-server-to-server': true,
    },
    edition: 'both',
  });
}
