import { ApiOpenApiRegistry, zOpenApi } from '../registry';

export function registerQuickBooksRoutes(registry: ApiOpenApiRegistry) {
  const tag = 'Integrations - QuickBooks';

  const QboOAuthCallbackQuery = registry.registerSchema(
    'QboOAuthCallbackQuery',
    zOpenApi.object({
      code: zOpenApi.string().optional().describe('OAuth 2.0 authorization code returned by Intuit. Required unless Intuit sends an error parameter.'),
      state: zOpenApi.string().optional().describe('Base64url-encoded JSON containing tenantId and csrf generated by the connect endpoint.'),
      realmId: zOpenApi.string().optional().describe('QuickBooks company/realm ID returned by Intuit.'),
      error: zOpenApi.string().optional().describe('OAuth error returned by Intuit when authorization fails or is denied.'),
    }),
  );

  const QboErrorResponse = registry.registerSchema(
    'QboErrorResponse',
    zOpenApi.object({
      error: zOpenApi.string().describe('Error message returned by middleware or by the connect endpoint.'),
    }),
  );

  const QboRouteMissingResponse = registry.registerSchema(
    'QboRouteMissingResponse',
    zOpenApi.string().describe('Default Next.js 404 page or not-found response. The route file listed in inventory is absent in this worktree.'),
  );

  registry.registerRoute({
    method: 'get',
    path: '/api/integrations/qbo/status',
    summary: 'QuickBooks Online status route unavailable',
    description:
      'This path appears in the generated route inventory, but server/src/app/api/integrations/qbo/status/route.ts is not present in the current worktree. Without an x-api-key, API middleware returns 401 before routing. With the middleware requirement satisfied, Next.js has no handler for this path and returns the framework not-found response. QuickBooks connection status is currently exposed through server actions such as getQboConnectionStatus and through versioned QuickBooks API routes, not this inventory-only path.',
    tags: [tag],
    security: [{ ApiKeyAuth: [] }],
    deprecated: true,
    responses: {
      401: {
        description: 'x-api-key is missing at middleware before routing.',
        schema: QboErrorResponse,
      },
      404: {
        description: 'No route handler exists for this inventory-only path in the current worktree.',
        contentType: 'text/html',
        schema: QboRouteMissingResponse,
      },
    },
    extensions: {
      'x-route-inventory-only': true,
      'x-route-file-missing': 'server/src/app/api/integrations/qbo/status/route.ts',
      'x-oauth-provider': 'quickbooks-online',
    },
    edition: 'both',
  });

  registry.registerRoute({

    method: 'get',
    path: '/api/integrations/qbo/connect',
    summary: 'Start QuickBooks Online OAuth flow',
    description:
      'Browser-navigated endpoint that initiates the QuickBooks Online OAuth 2.0 authorization flow. The handler resolves tenant context with createTenantKnex, reads qbo_client_id from app secrets, generates a random CSRF value, embeds {tenantId, csrf} as base64url JSON in the state parameter, and redirects to Intuit at appcenter.intuit.com/connect/oauth2. The CSRF value is currently logged but not persisted, and the callback currently treats CSRF as valid. The route is not currently listed in apiKeySkipPaths, so middleware may require x-api-key before the browser can reach the handler.',
    tags: [tag],
    security: [{ ApiKeyAuth: [] }],
    responses: {
      302: {
        description:
          'Redirect to Intuit OAuth authorization URL. Location includes client_id, response_type=code, QuickBooks accounting scope, redirect_uri, and encoded state. The handler returns no JSON body.',
        emptyBody: true,
      },
      401: {
        description: 'Tenant context is missing in the handler, or x-api-key is missing at middleware before the handler runs.',
        schema: QboErrorResponse,
      },
      500: {
        description: 'QBO client ID is not configured, or an unexpected error occurred while constructing the authorization redirect.',
        schema: QboErrorResponse,
      },
    },
    extensions: {
      'x-oauth-provider': 'quickbooks-online',
      'x-redirect-endpoint': true,
      'x-middleware-api-key-required-currently': true,
      'x-csrf-validation-implemented': false,
    },
    edition: 'both',
  });

  registry.registerRoute({
    method: 'get',
    path: '/api/integrations/qbo/callback',
    summary: 'Handle QuickBooks Online OAuth callback',
    description:
      'OAuth 2.0 redirect endpoint for QuickBooks Online. Intuit redirects the browser here with code, state, and realmId after authorization. The handler decodes tenantId and csrf from the base64url state parameter, exchanges the code for access and refresh tokens, stores credentials in the tenant secret qbo_credentials keyed by realmId, and redirects back to /msp/settings with qbo_status=success or qbo_status=failure and an error code. The route returns redirects rather than JSON from the handler. Like the connect route, it is not currently listed in apiKeySkipPaths, so middleware may reject real Intuit callbacks that do not include x-api-key.',
    tags: [tag],
    security: [],
    request: {
      query: QboOAuthCallbackQuery,
    },
    responses: {
      307: {
        description:
          'Redirect to the MSP settings integrations page. Success redirects with qbo_status=success; failures redirect with qbo_status=failure and an error such as qbo_error, missing_params, invalid_state, csrf_mismatch, config_error, token_exchange_failed, or callback_processing_error. The handler returns no JSON body.',
        emptyBody: true,
      },
      401: {
        description: 'Middleware-level API-key rejection can occur before the OAuth callback handler runs.',
        schema: QboErrorResponse,
      },
    },
    extensions: {
      'x-oauth-provider': 'quickbooks-online',
      'x-redirect-endpoint': true,
      'x-token-secret-name': 'qbo_credentials',
      'x-middleware-api-key-required-currently': true,
      'x-csrf-validation-implemented': false,
    },
    edition: 'both',
  });
}
