# Test values with temporal worker enabled
temporal-worker:
  enabled: true
  db:
    host: "postgresql.default.svc.cluster.local"
    port: "5432"
    serverDatabase: "msp_server"
    user: "msp_server"
    serverPasswordSecret:
      name: "alga-psa-db-secrets"
      key: "server-password"
    adminPasswordSecret:
      name: "alga-psa-db-secrets"
      key: "admin-password"
  email:
    resendApiKeySecret:
      name: "alga-psa-secrets"
      key: "RESEND_API_KEY"
  applicationUrl: "https://test.algapsa.com"
  vault:
    enabled: false
  secrets:
    internalApiSharedSecret: "test-internal-api-secret"
    algaAuthKey: "test-alga-auth-key"