x-common-config: &common-config
  build:
    context: ..
    dockerfile: setup/Dockerfile
  container_name: setup
  command: "/app/entrypoint.sh"
  environment:
    DB_HOST: ${DB_HOST}
    DB_PORT: ${DB_PORT}
    DB_NAME: ${DB_NAME}
    DB_USER: postgres
    
    DB_NAME_HOCUSPOCUS: ${DB_NAME_HOCUSPOCUS}
    DB_USER_HOCUSPOCUS: ${DB_USER_HOCUSPOCUS}
    DB_NAME_SERVER: ${DB_NAME_SERVER}
    DB_USER_SERVER: postgres
    APP_NAME: ${APP_NAME}
    APP_ENV: ${APP_ENV}
    DB_TYPE: ${DB_TYPE}
    POSTGRES_USER: postgres

services:
  setup:
    <<: *common-config
    networks:
      - ${NETWORK_NAME:-app-network}
    volumes:
      - type: bind
        source: ../secrets/postgres_password
        target: /run/secrets/postgres_password
        read_only: true
    secrets:
      - postgres_password
      - db_password_server

secrets:
  postgres_password:
    file: ../secrets/postgres_password
  db_password_server:
    file: ../secrets/db_password_server

networks:
  app-network:
    external: ${USE_EXTERNAL_NETWORK:-true}
