#!/usr/bin/env bash
# Generate gitignored .env files for the local Co-Managed IT dev workers from
# server/.env.local and the local secrets/ directory. No secret values live in
# this script; outputs (ee/temporal-workflows/.env, services/workflow-worker/.env)
# are gitignored.
#
# Layout this script assumes (see docs/plans/co-managed-local-dev-environment.md):
#   - app server:        localhost:3374 (board-owned service, npm run dev)
#   - isolated database: server_co_managed on the alga-psa-local-test postgres
#                        (direct 127.0.0.1:5472 — pgbouncer only routes "server")
#   - temporal dev:      docker container co-managed-it-temporal-dev, 127.0.0.1:7374
#   - redis:             shared alga-psa-local-test redis with branch-specific
#                        stream prefixes (no cross-worktree event consumption)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_LOCAL="$REPO_ROOT/server/.env.local"
SECRETS_DIR="$REPO_ROOT/secrets"

get_env() { # get_env KEY — read KEY from server/.env.local
  local line
  line="$(grep -m1 "^$1=" "$ENV_LOCAL" || true)"
  [[ -n "$line" ]] || { echo "missing $1 in server/.env.local" >&2; exit 1; }
  printf '%s' "${line#*=}"
}

get_secret_file() { # get_secret_file NAME
  [[ -s "$SECRETS_DIR/$1" ]] || { echo "missing secrets/$1" >&2; exit 1; }
  tr -d '\n' < "$SECRETS_DIR/$1"
}

DB_PASSWORD_SERVER="$(get_env DB_PASSWORD_SERVER)"
DB_PASSWORD_ADMIN="$(get_env DB_PASSWORD_ADMIN)"
REDIS_PASSWORD="$(get_env REDIS_PASSWORD)"
NEXTAUTH_SECRET="$(get_env NEXTAUTH_SECRET)"
DB_NAME_SERVER="$(get_env DB_NAME_SERVER)"
DB_HOST="$(get_env DB_HOST)"
DB_PORT="$(get_env DB_PORT)"
REDIS_HOST="$(get_env REDIS_HOST)"
REDIS_PORT="$(get_env REDIS_PORT)"
TEMPORAL_ADDRESS="$(get_env TEMPORAL_ADDRESS)"
APPLICATION_URL="$(get_env APPLICATION_URL)"
ALGA_AUTH_KEY="$(get_secret_file alga_auth_key)"
CREDENTIAL_ENCRYPTION_KEY="$(get_secret_file credential_encryption_key)"

umask 077

cat > "$REPO_ROOT/ee/temporal-workflows/.env" <<EOF
# Generated by scripts/dev/generate-co-managed-worker-env.sh — do not commit.
NODE_ENV=development
APP_ENV=development
EDITION=enterprise
LOG_LEVEL=info
DB_TYPE=postgres
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME_SERVER=$DB_NAME_SERVER
DB_USER_SERVER=app_user
DB_USER_ADMIN=postgres
DB_PASSWORD_SERVER=$DB_PASSWORD_SERVER
DB_PASSWORD_ADMIN=$DB_PASSWORD_ADMIN
TEMPORAL_ADDRESS=$TEMPORAL_ADDRESS
TEMPORAL_NAMESPACE=default
TEMPORAL_TASK_QUEUE=tenant-workflows
TEMPORAL_TASK_QUEUES=tenant-workflows,portal-domain-workflows,email-domain-workflows,alga-jobs,sla-workflows
TEMPORAL_JOB_TASK_QUEUE=alga-jobs
APPLICATION_URL=$APPLICATION_URL
NEXTAUTH_URL=$APPLICATION_URL
NEXT_PUBLIC_BASE_URL=$APPLICATION_URL
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ALGA_AUTH_KEY=$ALGA_AUTH_KEY
CREDENTIAL_ENCRYPTION_KEY=$CREDENTIAL_ENCRYPTION_KEY
REDIS_HOST=$REDIS_HOST
REDIS_PORT=$REDIS_PORT
REDIS_PASSWORD=$REDIS_PASSWORD
REDIS_PREFIX=alga-psa-comanaged:
WORKFLOW_REDIS_STREAM_PREFIX=comanaged:workflow:events:
ENABLE_HEALTH_CHECK=true
HEALTH_CHECK_PORT=8375
EOF

cat > "$REPO_ROOT/services/workflow-worker/.env" <<EOF
# Generated by scripts/dev/generate-co-managed-worker-env.sh — do not commit.
NODE_ENV=development
APP_ENV=development
EDITION=enterprise
LOG_LEVEL=info
DB_TYPE=postgres
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME_SERVER
DB_NAME_SERVER=$DB_NAME_SERVER
PGBOSS_DATABASE=$DB_NAME_SERVER
DB_USER_SERVER=app_user
DB_USER_ADMIN=postgres
DB_PASSWORD_SERVER=$DB_PASSWORD_SERVER
DB_PASSWORD_ADMIN=$DB_PASSWORD_ADMIN
TEMPORAL_ADDRESS=$TEMPORAL_ADDRESS
TEMPORAL_NAMESPACE=default
TEMPORAL_JOB_TASK_QUEUE=alga-jobs
APPLICATION_URL=$APPLICATION_URL
NEXTAUTH_URL=$APPLICATION_URL
HOST=$APPLICATION_URL
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ALGA_AUTH_KEY=$ALGA_AUTH_KEY
CREDENTIAL_ENCRYPTION_KEY=$CREDENTIAL_ENCRYPTION_KEY
REDIS_HOST=$REDIS_HOST
REDIS_PORT=$REDIS_PORT
REDIS_PASSWORD=$REDIS_PASSWORD
REDIS_PREFIX=alga-psa-comanaged:
WORKFLOW_WORKER_MODE=v2
WORKFLOW_DISTRIBUTED_MODE=true
WORKFLOW_REDIS_STREAM_PREFIX=comanaged:workflow:events:
WORKFLOW_REDIS_CONSUMER_GROUP=workflow-workers
PORT=4374
EOF

echo "wrote ee/temporal-workflows/.env and services/workflow-worker/.env"

# The temporal worker's dist runtime resolves onboarding seeds from
# dist/seeds/onboarding (Docker parity: ee/temporal-workflows/Dockerfile copies
# them there). A local `npm run build` (tsc) does not, so replicate the copy —
# without it coManagedProvisioningWorkflow fails its seeds step with ENOENT.
TW_DIST="$REPO_ROOT/ee/temporal-workflows/dist"
if [[ -d "$TW_DIST" ]]; then
  rm -rf "$TW_DIST/seeds"
  mkdir -p "$TW_DIST/seeds"
  cp -r "$REPO_ROOT/ee/server/seeds/onboarding" "$TW_DIST/seeds/onboarding"
  cp -r "$REPO_ROOT/server/migrations/utils/permissions" "$TW_DIST/seeds/permissions"
  cp "$REPO_ROOT/server/migrations/utils/tenantDb.cjs" "$TW_DIST/seeds/tenantDb.cjs"
  echo "copied onboarding seeds into ee/temporal-workflows/dist/seeds"
fi
