{{- if .Values.devEnv.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sebastian.fullname" . }}-copy-harbor-credentials
  namespace: {{ .Values.devEnv.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"  # After namespace creation (-20) but before other secrets (-10)
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: copy-harbor-credentials
    spec:
      serviceAccountName: {{ include "sebastian.fullname" . }}-harbor-copy-sa
      restartPolicy: Never
      containers:
        - name: copy-credentials
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Copying harbor-credentials from msp namespace..."
              kubectl get secret harbor-credentials -n msp -o yaml | \
                sed 's/namespace: msp/namespace: {{ .Values.devEnv.namespace }}/' | \
                kubectl apply -f -
              echo "Harbor credentials copied successfully"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sebastian.fullname" . }}-harbor-copy-sa
  namespace: {{ .Values.devEnv.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-18"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sebastian.fullname" . }}-harbor-copy-role
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-18"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "apply", "patch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sebastian.fullname" . }}-harbor-copy-binding
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-18"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ include "sebastian.fullname" . }}-harbor-copy-sa
  namespace: {{ .Values.devEnv.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "sebastian.fullname" . }}-harbor-copy-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}