{{- if .Values.devEnv.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.devEnv.namespace }}
  labels:
    name: {{ .Values.devEnv.namespace }}
    type: dev-environment
    branch: "{{ .Values.devEnv.sanitizedBranch }}"
    {{- include "sebastian.labels" . | nindent 4 }}
{{- end }}