{{- if .Values.temporalWorker.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sebastian.fullname" . }}-temporal-worker
  namespace: {{ include "sebastian.namespace" . }}
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-worker
data:
  # Worker configuration
  worker-config.json: |
    {
      "temporal": {
        "address": "{{ .Values.temporalWorker.temporal.address }}",
        "namespace": "{{ .Values.temporalWorker.temporal.namespace }}",
        "taskQueue": "{{ .Values.temporalWorker.temporal.taskQueue }}",
        "maxConcurrentActivityExecutions": {{ .Values.temporalWorker.temporal.maxConcurrentActivityExecutions | default 10 }},
        "maxConcurrentWorkflowTaskExecutions": {{ .Values.temporalWorker.temporal.maxConcurrentWorkflowTaskExecutions | default 10 }}
      },
      "logging": {
        "level": "{{ .Values.temporalWorker.logLevel }}",
        "format": "json"
      },
      "healthCheck": {
        "enabled": true,
        "port": 8080,
        "path": "/health"
      }
    }
{{- end }}