{{- if and .Values.temporalWorker.enabled .Values.temporalWorker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sebastian.fullname" . }}-temporal-worker
  namespace: {{ include "sebastian.namespace" . }}
  labels:
    {{- include "sebastian.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sebastian.fullname" . }}-temporal-worker
  minReplicas: {{ .Values.temporalWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.temporalWorker.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.temporalWorker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.temporalWorker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.temporalWorker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.temporalWorker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.temporalWorker.autoscaling.customMetrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.temporalWorker.autoscaling.behavior.scaleDown.stabilizationWindowSeconds | default 300 }}
      policies:
      - type: Percent
        value: {{ .Values.temporalWorker.autoscaling.behavior.scaleDown.percent | default 10 }}
        periodSeconds: {{ .Values.temporalWorker.autoscaling.behavior.scaleDown.periodSeconds | default 60 }}
      - type: Pods
        value: {{ .Values.temporalWorker.autoscaling.behavior.scaleDown.pods | default 1 }}
        periodSeconds: {{ .Values.temporalWorker.autoscaling.behavior.scaleDown.periodSeconds | default 60 }}
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.temporalWorker.autoscaling.behavior.scaleUp.stabilizationWindowSeconds | default 60 }}
      policies:
      - type: Percent
        value: {{ .Values.temporalWorker.autoscaling.behavior.scaleUp.percent | default 100 }}
        periodSeconds: {{ .Values.temporalWorker.autoscaling.behavior.scaleUp.periodSeconds | default 60 }}
      - type: Pods
        value: {{ .Values.temporalWorker.autoscaling.behavior.scaleUp.pods | default 2 }}
        periodSeconds: {{ .Values.temporalWorker.autoscaling.behavior.scaleUp.periodSeconds | default 60 }}
      selectPolicy: Max
{{- end }}