{{- if and .Values.enabled (not .Values.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workflow-worker.fullname" . }}-secrets
  namespace: {{ include "workflow-worker.namespace" . }}
  labels:
    {{- include "workflow-worker.labels" . | nindent 4 }}
    app.kubernetes.io/component: workflow-worker
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | quote }}
  TOKEN_SECRET_KEY: {{ .Values.secrets.tokenSecretKey | quote }}
  CRYPTO_KEY: {{ .Values.secrets.cryptoKey | quote }}
{{- end }}

