'use client';

import Link from 'next/link';
import React, { useMemo, useState } from 'react';
import useSWR from 'swr';
import { CalendarDays, CheckCircle2, List, Pause, Plus, Search, SkipForward } from 'lucide-react';
import { Button } from '@alga-psa/ui/components/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@alga-psa/ui/components/Card';
import { Dialog, DialogContent } from '@alga-psa/ui/components/Dialog';
import { Input } from '@alga-psa/ui/components/Input';
import { Label } from '@alga-psa/ui/components/Label';
import { TextArea } from '@alga-psa/ui/components/TextArea';
import { Badge } from '@alga-psa/ui/components/Badge';
import { useAssetCrossFeature } from '../context/AssetCrossFeatureContext';
import { completeOccurrence, createOccurrenceTicket, getMaintenanceAggregates, listMaintenanceOccurrences, setSchedulePaused, skipOccurrence } from '../actions/assetActions';
import { advanceMaintenanceDate } from '../lib/maintenanceRecurrence';
import { unwrapAssetActionResult } from '../actions/assetActionErrors';
import type { AssetMaintenanceOccurrence, AssetMaintenanceOccurrenceStatus, MaintenanceOccurrenceFilters } from '@alga-psa/types';

type View = 'queue' | 'plans' | 'history';
type QueueMode = 'list' | 'calendar';
const startOfDay = (date: Date) => new Date(date.getFullYear(), date.getMonth(), date.getDate());
const dateLabel = (date: string) => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date));

function tone(occurrence: AssetMaintenanceOccurrence) {
  if (occurrence.status !== 'open') return 'secondary' as const;
  const due = startOfDay(new Date(occurrence.due_date)); const today = startOfDay(new Date());
  return due < today ? 'error' as const : due.getTime() === today.getTime() ? 'warning' as const : 'info' as const;
}

export function MaintenanceCommandCenter() {
  const [tab, setTab] = useState<View>('queue'); const [mode, setMode] = useState<QueueMode>('list');
  const [search, setSearch] = useState(''); const [status, setStatus] = useState<AssetMaintenanceOccurrenceStatus | 'all'>('open');
  const [clientId, setClientId] = useState(''); const [assetType, setAssetType] = useState(''); const [maintenanceType, setMaintenanceType] = useState('');
  const [dueFrom, setDueFrom] = useState(''); const [dueTo, setDueTo] = useState('');
  const [selected, setSelected] = useState<AssetMaintenanceOccurrence | null>(null);
  const [ticketTarget, setTicketTarget] = useState<AssetMaintenanceOccurrence | null>(null);
  const [completeTarget, setCompleteTarget] = useState<AssetMaintenanceOccurrence | null>(null);
  const [skipTarget, setSkipTarget] = useState<AssetMaintenanceOccurrence | null>(null);
  const [performedAt, setPerformedAt] = useState(() => new Date().toISOString().slice(0, 10)); const [notes, setNotes] = useState(''); const [skipReason, setSkipReason] = useState('');
  const { renderQuickAddTicket } = useAssetCrossFeature();
  const filters = useMemo<MaintenanceOccurrenceFilters>(() => ({ status: status === 'all' ? undefined : [status], search: search || undefined, client_id: clientId || undefined, asset_type: assetType || undefined, maintenance_type: maintenanceType as MaintenanceOccurrenceFilters['maintenance_type'] || undefined, due_from: dueFrom || undefined, due_to: dueTo || undefined, limit: 100 }), [assetType, clientId, dueFrom, dueTo, maintenanceType, search, status]);
  const { data, mutate, isLoading } = useSWR(['maintenance-occurrences', filters], () => listMaintenanceOccurrences(filters).then(unwrapAssetActionResult));
  const { data: aggregates, mutate: mutateAggregates } = useSWR('maintenance-aggregates', () => getMaintenanceAggregates().then(unwrapAssetActionResult));
  const occurrences = data?.occurrences ?? [];
  const clientOptions = Array.from(new Map(occurrences.filter((item) => item.client_id && item.client_name).map((item) => [item.client_id!, item.client_name!])).entries());
  const assetTypeOptions = Array.from(new Set(occurrences.map((item) => item.asset_type).filter(Boolean))) as string[];
  const maintenanceTypeOptions = Array.from(new Set(occurrences.map((item) => item.maintenance_type).filter(Boolean))) as string[];
  const refresh = async () => { await Promise.all([mutate(), mutateAggregates()]); setSelected(null); };
  const complete = async () => { if (!completeTarget) return; await unwrapAssetActionResult(await completeOccurrence({ occurrence_id: completeTarget.occurrence_id, asset_id: completeTarget.asset_id, performed_at: new Date(performedAt).toISOString(), notes, maintenance_data: { checklist_completed: true } })); setCompleteTarget(null); setNotes(''); await refresh(); };
  const skip = async () => { if (!skipTarget || !skipReason.trim()) return; await unwrapAssetActionResult(await skipOccurrence(skipTarget.occurrence_id, skipReason)); setSkipTarget(null); setSkipReason(''); await refresh(); };
  // Plans remains an occurrence-backed plan queue until a schedule-list action is introduced.
  const shown = tab === 'plans' ? occurrences.filter((o) => o.status === 'open') : tab === 'history' ? occurrences.filter((o) => o.status !== 'open') : occurrences;
  return <div className="h-full min-h-0 overflow-auto bg-[rgb(var(--color-background))] p-4 md:p-6" data-automation-id="maintenance-command-center">
    <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold text-[rgb(var(--color-text-900))]">Maintenance Command Center</h1><p className="text-sm text-[rgb(var(--color-text-600))]">Next due advances from the actual completion date.</p></div><Link id="maintenance-back-to-assets-link" href="/msp/assets" className="text-sm text-[rgb(var(--color-primary-600))]">Assets</Link></div>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['Overdue', aggregates?.overdue ?? 0], ['Due today', aggregates?.due_today ?? 0], ['Upcoming 7d', aggregates?.upcoming_7d ?? 0], ['Open tickets', aggregates?.open_maintenance_tickets ?? 0], ['Compliance 90d', `${(aggregates?.compliance_90d ?? 0).toFixed(0)}%`]].map(([label, value]) => <button key={label} id={`maintenance-kpi-${String(label).toLowerCase().replaceAll(' ', '-')}`} onClick={() => { setTab('queue'); setStatus('open'); }} className="rounded-lg border border-[rgb(var(--color-border-200))] bg-[rgb(var(--color-card))] p-4 text-left shadow-sm"><div className="text-xs font-medium uppercase tracking-wide text-[rgb(var(--color-text-500))]">{label}</div><div className="mt-1 text-2xl font-semibold text-[rgb(var(--color-text-900))]">{value}</div></button>)}</div>
    <div className="mb-4 flex flex-wrap gap-2 border-b border-[rgb(var(--color-border-200))] pb-3">{(['queue', 'plans', 'history'] as View[]).map((item) => <Button key={item} id={`maintenance-view-${item}`} size="sm" variant={tab === item ? 'default' : 'ghost'} onClick={() => { setTab(item); setStatus(item === 'history' ? 'all' : 'open'); }}>{item === 'queue' ? 'Work queue' : item === 'plans' ? 'Plan queue' : 'History'}</Button>)}</div>
    {tab === 'queue' && <div className="mb-4 flex flex-wrap gap-2"><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[rgb(var(--color-text-500))]" /><Input id="maintenance-search" className="pl-9" placeholder="Search plans, assets, or clients" value={search} onChange={(event) => setSearch(event.target.value)} /></div><select id="maintenance-status-filter" value={status} onChange={(event) => setStatus(event.target.value as AssetMaintenanceOccurrenceStatus | 'all')} className="rounded-md border border-[rgb(var(--color-border-200))] bg-[rgb(var(--color-card))] px-3 text-sm"><option value="open">Actionable</option><option value="all">All statuses</option><option value="completed">Completed</option><option value="skipped">Skipped</option></select><select id="maintenance-client-filter" value={clientId} onChange={(event) => setClientId(event.target.value)} className="rounded-md border border-[rgb(var(--color-border-200))] bg-[rgb(var(--color-card))] px-3 text-sm"><option value="">All clients</option>{clientOptions.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select id="maintenance-asset-type-filter" value={assetType} onChange={(event) => setAssetType(event.target.value)} className="rounded-md border border-[rgb(var(--color-border-200))] bg-[rgb(var(--color-card))] px-3 text-sm"><option value="">All asset types</option>{assetTypeOptions.map((item) => <option key={item} value={item}>{item}</option>)}</select><select id="maintenance-plan-type-filter" value={maintenanceType} onChange={(event) => setMaintenanceType(event.target.value)} className="rounded-md border border-[rgb(var(--color-border-200))] bg-[rgb(var(--color-card))] px-3 text-sm"><option value="">All plan types</option>{maintenanceTypeOptions.map((item) => <option key={item} value={item}>{item}</option>)}</select><Input id="maintenance-due-from-filter" type="date" value={dueFrom} onChange={(event) => setDueFrom(event.target.value)} /><Input id="maintenance-due-to-filter" type="date" value={dueTo} onChange={(event) => setDueTo(event.target.value)} /><Button id="maintenance-list-toggle" size="sm" variant={mode === 'list' ? 'default' : 'outline'} onClick={() => setMode('list')}><List className="mr-1 h-4 w-4" />List</Button><Button id="maintenance-calendar-toggle" size="sm" variant={mode === 'calendar' ? 'default' : 'outline'} onClick={() => setMode('calendar')}><CalendarDays className="mr-1 h-4 w-4" />Calendar</Button></div>}
    <div className="grid min-h-[480px] gap-4 xl:grid-cols-[minmax(0,44%)_minmax(0,1fr)]"><Card><CardHeader><CardTitle className="text-base">{tab === 'queue' ? 'Actionable occurrences' : tab === 'plans' ? 'Active plan queue (occurrence-backed)' : 'History'}</CardTitle></CardHeader><CardContent>{isLoading ? <p className="text-sm text-[rgb(var(--color-text-500))]">Loading maintenance…</p> : mode === 'calendar' && tab === 'queue' ? <Calendar occurrences={shown} onSelect={setSelected} /> : <OccurrenceList occurrences={shown} onSelect={setSelected} />}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Occurrence detail</CardTitle></CardHeader><CardContent>{selected ? <Detail occurrence={selected} onTicket={() => setTicketTarget(selected)} onComplete={() => { setPerformedAt(new Date().toISOString().slice(0, 10)); setCompleteTarget(selected); }} onSkip={() => setSkipTarget(selected)} onPause={async () => { await unwrapAssetActionResult(await setSchedulePaused(selected.schedule_id, true)); await refresh(); }} /> : <p className="text-sm text-[rgb(var(--color-text-500))]">Select an occurrence to see its asset, plan, ticket, and execution actions.</p>}</CardContent></Card></div>
    {renderQuickAddTicket({ open: Boolean(ticketTarget), onOpenChange: (open) => !open && setTicketTarget(null), onTicketAdded: async (ticket) => { if (ticketTarget && ticket?.ticket_id) await unwrapAssetActionResult(await createOccurrenceTicket(ticketTarget.occurrence_id, ticket.ticket_id)); setTicketTarget(null); await refresh(); }, prefilledClient: ticketTarget?.client_id && ticketTarget.client_name ? { id: ticketTarget.client_id, name: ticketTarget.client_name } : undefined, assetId: ticketTarget?.asset_id, assetName: ticketTarget?.asset_name, prefilledTitle: ticketTarget ? `Maintenance: ${ticketTarget.schedule_name}` : undefined, prefilledDescription: ticketTarget ? `${ticketTarget.maintenance_type} maintenance due ${dateLabel(ticketTarget.due_date)}. Occurrence: ${ticketTarget.occurrence_id}` : undefined, prefilledDueDate: ticketTarget?.due_date })}
    <Dialog isOpen={Boolean(completeTarget)} onClose={() => setCompleteTarget(null)} title="Complete maintenance" id="complete-maintenance-dialog" footer={<div className="flex justify-end gap-2"><Button id="cancel-maintenance-completion" variant="secondary" onClick={() => setCompleteTarget(null)}>Cancel</Button><Button id="confirm-maintenance-completion" onClick={complete}>Complete</Button></div>}><DialogContent><div className="space-y-4"><div><Label htmlFor="maintenance-performed-date">Performed date</Label><Input id="maintenance-performed-date" type="date" value={performedAt} onChange={(event) => setPerformedAt(event.target.value)} /></div><p className="rounded-md bg-[rgb(var(--color-primary-50))] p-3 text-sm text-[rgb(var(--color-text-700))]">Next due advances from this completion date to <strong>{completeTarget ? dateLabel(advanceMaintenanceDate(new Date(performedAt), completeTarget.frequency || 'monthly', completeTarget.frequency_interval || 1).toISOString()) : ''}</strong>.</p><div><Label htmlFor="maintenance-completion-notes">Notes</Label><TextArea id="maintenance-completion-notes" value={notes} onChange={(event) => setNotes(event.target.value)} rows={4} /></div></div></DialogContent></Dialog>
    <Dialog isOpen={Boolean(skipTarget)} onClose={() => setSkipTarget(null)} title="Skip maintenance" id="skip-maintenance-dialog" footer={<div className="flex justify-end gap-2"><Button id="cancel-maintenance-skip" variant="secondary" onClick={() => setSkipTarget(null)}>Cancel</Button><Button id="confirm-maintenance-skip" onClick={skip} disabled={!skipReason.trim()}>Skip</Button></div>}><DialogContent><Label htmlFor="maintenance-skip-reason">Reason</Label><TextArea id="maintenance-skip-reason" value={skipReason} onChange={(event) => setSkipReason(event.target.value)} rows={3} /></DialogContent></Dialog>
  </div>;
}

function OccurrenceList({ occurrences, onSelect }: { occurrences: AssetMaintenanceOccurrence[]; onSelect: (occurrence: AssetMaintenanceOccurrence) => void }) { if (!occurrences.length) return <p className="py-10 text-center text-sm text-[rgb(var(--color-text-500))]">No maintenance occurrences match these filters.</p>; return <div className="space-y-2">{occurrences.map((occurrence) => <button id={`maintenance-occurrence-${occurrence.occurrence_id}`} key={occurrence.occurrence_id} onClick={() => onSelect(occurrence)} className="w-full rounded-md border border-[rgb(var(--color-border-200))] p-3 text-left hover:bg-[rgb(var(--color-primary-50))]"><div className="flex items-start justify-between gap-2"><div><div className="font-medium text-[rgb(var(--color-text-900))]">{occurrence.schedule_name}</div><div className="text-xs text-[rgb(var(--color-text-600))]">{occurrence.client_name || 'Unassigned client'} · {occurrence.asset_name}</div></div><Badge variant={tone(occurrence)}>{occurrence.status === 'open' ? dateLabel(occurrence.due_date) : occurrence.status}</Badge></div></button>)}</div>; }
function Calendar({ occurrences, onSelect }: { occurrences: AssetMaintenanceOccurrence[]; onSelect: (occurrence: AssetMaintenanceOccurrence) => void }) { const groups = occurrences.reduce<Record<string, AssetMaintenanceOccurrence[]>>((all, occurrence) => { const key = new Date(occurrence.due_date).toISOString().slice(0, 10); (all[key] ||= []).push(occurrence); return all; }, {}); return <div className="grid grid-cols-7 gap-2">{Object.entries(groups).map(([day, values]) => <div key={day} className="min-h-24 rounded-md border border-[rgb(var(--color-border-200))] p-2"><div className="mb-1 text-xs font-medium">{dateLabel(day)}</div>{values.map((occurrence) => <button id={`maintenance-calendar-occurrence-${occurrence.occurrence_id}`} key={occurrence.occurrence_id} onClick={() => onSelect(occurrence)} className="mb-1 block w-full truncate rounded px-1 text-left text-xs text-[rgb(var(--color-primary-700))]">{occurrence.schedule_name}</button>)}</div>)}</div>; }
function Detail({ occurrence, onTicket, onComplete, onSkip, onPause }: { occurrence: AssetMaintenanceOccurrence; onTicket: () => void; onComplete: () => void; onSkip: () => void; onPause: () => void }) { return <div className="flex h-full flex-col gap-5"><div className="flex items-center justify-between"><Badge variant={tone(occurrence)}>{occurrence.status}</Badge><span className="text-sm text-[rgb(var(--color-text-600))]">Due {dateLabel(occurrence.due_date)}</span></div><div className="grid grid-cols-2 gap-3 text-sm"><div><div className="text-[rgb(var(--color-text-500))]">Asset</div><Link id="maintenance-detail-asset-link" className="text-[rgb(var(--color-primary-600))]" href={`/msp/assets/${occurrence.asset_id}`}>{occurrence.asset_name || occurrence.asset_id}</Link></div><div><div className="text-[rgb(var(--color-text-500))]">Plan</div><div>{occurrence.schedule_name}</div></div><div><div className="text-[rgb(var(--color-text-500))]">Cadence</div><div>Every {occurrence.frequency_interval} {occurrence.frequency}</div></div><div><div className="text-[rgb(var(--color-text-500))]">Type</div><div className="capitalize">{occurrence.maintenance_type}</div></div>{occurrence.ticket_id && <div><div className="text-[rgb(var(--color-text-500))]">Linked ticket</div><Link id="maintenance-linked-ticket" className="text-[rgb(var(--color-primary-600))]" href={`/msp/tickets/${occurrence.ticket_id}`}>{occurrence.ticket_title || occurrence.ticket_id}</Link></div>}</div>{occurrence.status === 'open' && <div className="mt-auto flex flex-wrap gap-2">{occurrence.ticket_id ? <Link id="maintenance-open-ticket" href={`/msp/tickets/${occurrence.ticket_id}`} className="inline-flex items-center rounded-md border border-[rgb(var(--color-border-200))] px-3 py-1.5 text-sm"><Plus className="mr-1 h-4 w-4" />Open ticket</Link> : <Button id="maintenance-create-ticket" size="sm" variant="outline" onClick={onTicket}><Plus className="mr-1 h-4 w-4" />Create ticket</Button>}<Button id="maintenance-complete-occurrence" size="sm" onClick={onComplete}><CheckCircle2 className="mr-1 h-4 w-4" />Complete</Button><Button id="maintenance-skip-occurrence" size="sm" variant="outline" onClick={onSkip}><SkipForward className="mr-1 h-4 w-4" />Skip</Button><Button id="maintenance-pause-schedule" size="sm" variant="ghost" onClick={onPause}><Pause className="mr-1 h-4 w-4" />Pause</Button></div>}</div>; }
