/**
 * Pure compute layer for billing charge math, shared by production invoice
 * generation (BillingEngine load -> delegate) and the EE contract simulator.
 *
 * Compute modules perform no I/O of their own: every external lookup flows
 * through the injected ChargeComputeTaxPorts, so a caller that supplies
 * read-only ports gets a guaranteed write-free computation. The engine
 * supplies ports backed by its cached helpers + TaxService, preserving
 * production behavior exactly.
 */

import type { ISO8601String } from "@alga-psa/types";

/**
 * Resolved service-period timing for a recurring charge. Structurally
 * identical to BillingEngine's internal ResolvedRecurringChargeTiming; the
 * engine passes its resolution straight through, the simulator builds one
 * from hypothetical periods generated by the shared cadence layer.
 */
export interface ChargeComputeTiming {
  duePosition: "arrears" | "advance";
  servicePeriodStart: ISO8601String;
  servicePeriodEnd: ISO8601String;
  servicePeriodStartExclusive: ISO8601String;
  servicePeriodEndExclusive: ISO8601String;
  coverageRatio: number;
}

export interface ChargeComputeTaxInfo {
  taxRegion: string | null;
  isTaxable: boolean;
}

export interface ChargeComputeTaxResult {
  taxAmount: number;
  taxRate: number;
}

/**
 * The tax/region lookups the charge math consumes. Production backs these
 * with BillingEngine's memoized helpers and TaxService (which may provision
 * default tax settings); the simulator backs them with strictly read-only
 * equivalents.
 */
export interface ChargeComputeTaxPorts {
  getTaxInfoFromService(service: {
    service_id?: string;
    tax_rate_id?: string | null;
  }): Promise<ChargeComputeTaxInfo>;
  getLocationTaxRegionCode(
    locationId: string | null | undefined,
  ): Promise<string | null>;
  getClientDefaultTaxRegionCode(clientId: string): Promise<string | null>;
  calculateTax(
    clientId: string,
    netAmountInCents: number,
    date: ISO8601String,
    regionCode: string,
    isTaxable: boolean,
    currencyCode: string,
  ): Promise<ChargeComputeTaxResult>;
}

export interface ChargeComputeClient {
  client_id: string;
  is_tax_exempt?: boolean | null;
}
