/**
 * Pure compute layer for billing charge math, shared by production invoice
 * generation (BillingEngine load -> delegate) and the EE contract simulator.
 *
 * Compute modules perform no I/O. Callers resolve tax, region, and client
 * settings during their load phase and pass the synchronous context below.
 */

import type { ISO8601String } from "@alga-psa/types";

/**
 * Resolved service-period timing for a recurring charge. Structurally
 * identical to BillingEngine's internal ResolvedRecurringChargeTiming; the
 * engine passes its resolution straight through, the simulator builds one
 * from hypothetical periods generated by the shared cadence layer.
 */
export interface ChargeComputeTiming {
  duePosition: "arrears" | "advance";
  servicePeriodStart: ISO8601String;
  servicePeriodEnd: ISO8601String;
  servicePeriodStartExclusive: ISO8601String;
  servicePeriodEndExclusive: ISO8601String;
  coverageRatio: number;
}

export interface ChargeComputeTaxInfo {
  taxRegion: string | null;
  isTaxable: boolean;
}

export interface ChargeComputeTaxResult {
  taxAmount: number;
  taxRate: number;
}

/**
 * The tax/region lookups the charge math consumes. Production and simulation
 * preload tenant-scoped tax rows before entering deterministic charge math;
 * only the production load phase may provision missing default tax settings.
 */
export interface ChargeComputeTaxContext {
  getTaxInfoFromService(service: {
    service_id?: string;
    tax_rate_id?: string | null;
  }): ChargeComputeTaxInfo;
  getLocationTaxRegionCode(
    locationId: string | null | undefined,
  ): string | null;
  getClientDefaultTaxRegionCode(clientId: string): string | null;
  calculateTax(
    clientId: string,
    netAmountInCents: number,
    date: ISO8601String,
    regionCode: string,
    isTaxable: boolean,
    currencyCode: string,
  ): ChargeComputeTaxResult;
}

/** @deprecated Use ChargeComputeTaxContext. */
export type ChargeComputeTaxPorts = ChargeComputeTaxContext;

export interface ChargeComputeClient {
  client_id: string;
  is_tax_exempt?: boolean | null;
}
