export const AMP_FORMAT_VERSION = '1.0.0';
export const AMP_ENTITY_TABLES = ['organizations', 'locations', 'contacts', 'tickets', 'ticket_comments', 'assets'] as const;
export const AMP_ALLOWLISTED_TABLES = ['amp_manifest', ...AMP_ENTITY_TABLES, 'external_identifiers', 'custom_field_values', 'package_diagnostics'] as const;
export type AmpEntityType = typeof AMP_ENTITY_TABLES[number];
export type AmpErrorCode = 'AMP_UNKNOWN_TABLE' | 'AMP_UNSUPPORTED_VERSION' | 'AMP_INVALID_MANIFEST' | 'AMP_INVALID_VALUE' | 'AMP_INVALID_REFERENCE' | 'AMP_FORBIDDEN_SQLITE_OBJECT' | 'AMP_LIMIT_EXCEEDED' | 'AMP_EXTENSION_FORBIDDEN' | 'AMP_CROSS_TENANT_REFERENCE';
export const AMP_ERROR_CODES: Record<AmpErrorCode, string> = {
  AMP_UNKNOWN_TABLE: 'Package contains a table that AMP does not allow.', AMP_UNSUPPORTED_VERSION: 'Package format version is not supported.', AMP_INVALID_MANIFEST: 'Package manifest is missing or invalid.', AMP_INVALID_VALUE: 'A package value does not meet AMP requirements.', AMP_INVALID_REFERENCE: 'A package relationship does not resolve.', AMP_FORBIDDEN_SQLITE_OBJECT: 'Package contains a forbidden SQLite object.', AMP_LIMIT_EXCEEDED: 'Package exceeds a configured security limit.', AMP_EXTENSION_FORBIDDEN: 'SQLite extensions are forbidden.', AMP_CROSS_TENANT_REFERENCE: 'Package references a target outside the migration tenant.'
};
export interface AmpManifest { format_version: string; package_id: string; created_at: string; producer_name: string; producer_version: string; source_system: string; source_instance_id?: string; content_sha256: string; capabilities_json?: string; }
export interface AmpRecord { package_record_id: string; source_record_id: string; external_identifier_namespace: string; created_at?: string; updated_at?: string; extension_json?: string; [key: string]: unknown; }
export const AMP_LIMITS = { packageBytes: 250 * 1024 * 1024, rowsPerEntity: 500_000, rowsPerPackage: 2_000_000, textBytes: 64 * 1024, extensionJsonBytes: 16 * 1024, extensionJsonDepth: 8 } as const;
export const AMP_COMPATIBILITY = { accepted: ['1.0.x'], additiveChanges: 'minor', breakingChanges: 'major' } as const;
export const AMP_SCHEMA_SQL = `CREATE TABLE amp_manifest (format_version TEXT NOT NULL, package_id TEXT NOT NULL, created_at TEXT NOT NULL, producer_name TEXT NOT NULL, producer_version TEXT NOT NULL, source_system TEXT NOT NULL, source_instance_id TEXT, content_sha256 TEXT NOT NULL, capabilities_json TEXT);\nCREATE TABLE organizations (package_record_id TEXT PRIMARY KEY, source_record_id TEXT NOT NULL, external_identifier_namespace TEXT NOT NULL, name TEXT NOT NULL, created_at TEXT, updated_at TEXT, extension_json TEXT);\nCREATE TABLE locations (package_record_id TEXT PRIMARY KEY, source_record_id TEXT NOT NULL, external_identifier_namespace TEXT NOT NULL, organization_package_record_id TEXT NOT NULL, name TEXT NOT NULL, created_at TEXT, updated_at TEXT, extension_json TEXT);\nCREATE TABLE contacts (package_record_id TEXT PRIMARY KEY, source_record_id TEXT NOT NULL, external_identifier_namespace TEXT NOT NULL, organization_package_record_id TEXT, location_package_record_id TEXT, email TEXT, first_name TEXT, last_name TEXT, created_at TEXT, updated_at TEXT, extension_json TEXT);\nCREATE TABLE tickets (package_record_id TEXT PRIMARY KEY, source_record_id TEXT NOT NULL, external_identifier_namespace TEXT NOT NULL, organization_package_record_id TEXT, location_package_record_id TEXT, requester_package_record_id TEXT, title TEXT NOT NULL, description TEXT, status_name TEXT, priority_name TEXT, created_at TEXT, updated_at TEXT, extension_json TEXT);\nCREATE TABLE ticket_comments (package_record_id TEXT PRIMARY KEY, source_record_id TEXT NOT NULL, external_identifier_namespace TEXT NOT NULL, ticket_package_record_id TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT, updated_at TEXT, extension_json TEXT);\nCREATE TABLE assets (package_record_id TEXT PRIMARY KEY, source_record_id TEXT NOT NULL, external_identifier_namespace TEXT NOT NULL, organization_package_record_id TEXT, name TEXT NOT NULL, created_at TEXT, updated_at TEXT, extension_json TEXT);`;
