name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build-image-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up test environment
        run: |
          # Create secrets directory
          mkdir -p secrets

          # Create sample secrets as shown in setup guide
          # Note: These are placeholders for the build process and might
          # need adjustment based on actual build requirements.
          # Real secrets are not needed for just building the image.
          echo "placeholder-password" > secrets/postgres_password
          echo "placeholder-password" > secrets/db_password_server
          echo "placeholder-password" > secrets/db_password_hocuspocus
          echo "placeholder-password" > secrets/redis_password
          echo "placeholder-key-32-chars-long-01" > secrets/alga_auth_key
          echo "placeholder-key-32-chars-long-02" > secrets/crypto_key
          echo "placeholder-key-32-chars-long-03" > secrets/token_secret_key
          echo "placeholder-key-32-chars-long-04" > secrets/nextauth_secret
          echo "placeholder-password" > secrets/email_password
          echo "placeholder-id" > secrets/google_oauth_client_id
          echo "placeholder-secret" > secrets/google_oauth_client_secret

          # Set permissions
          chmod 600 secrets/*

          # Copy and configure environment file
          cp .env.example .env

          # Configure required environment variables
          cat >> .env << EOL
          # Required variables from setup guide
          APP_VERSION=1.0.0
          APP_NAME=sebastian-pr-check
          APP_ENV=development
          APP_HOST=0.0.0.0
          APP_PORT=3000
          APP_EDITION=community

          # Database Configuration
          DB_TYPE=postgres
          DB_USER_ADMIN=postgres

          # Logging Configuration
          LOG_LEVEL=INFO
          LOG_IS_FORMAT_JSON=false
          LOG_IS_FULL_DETAILS=false

          # Email Configuration
          EMAIL_ENABLE=false
          EMAIL_FROM=noreply@example.com
          EMAIL_HOST=smtp.example.com
          EMAIL_PORT=587
          EMAIL_USERNAME=noreply@example.com

          # Authentication Configuration
          NEXTAUTH_URL=http://localhost:3000
          NEXTAUTH_SESSION_EXPIRES=86400

          # Optional Configuration
          REQUIRE_HOCUSPOCUS=false
          EOL

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Note: We skip login and push steps for PR checks
      
      - name: Set environment variables for build
        run: |
          # Export environment variables that will be used during the build
          echo "NEXTAUTH_SECRET=$(cat secrets/nextauth_secret)" >> $GITHUB_ENV
          echo "NEXTAUTH_URL=http://localhost:3000" >> $GITHUB_ENV
          echo "ALGA_AUTH_KEY=$(cat secrets/alga_auth_key)" >> $GITHUB_ENV

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.prod
          push: false # Ensure image is not pushed
          # Load the image into the local Docker daemon if needed for subsequent steps
          # load: true 
          # tags are optional if not pushing or loading, but can be useful for debugging
          tags: |
            ghcr.io/nine-minds/alga-psa:pr-${{ github.event.number }}
