import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest';
import type { Client } from '@temporalio/client';
import { TestWorkflowEnvironment } from '@temporalio/testing';
import { randomUUID } from 'node:crypto';

vi.hoisted(() => { vi.stubEnv('EMAIL_PROVIDER', 'mock'); });
import { Worker } from '@temporalio/worker';
import { generateTemporaryPassword, sendWelcomeEmail } from '../../activities/email-activities';
import { testEmailWorkflow } from '../../workflows/test-email-workflow';
import type { SendWelcomeEmailActivityInput } from '../../types/workflow-types';
import path from 'path';

describe('Email workflow with the explicit mock email provider', () => {
  let environment: TestWorkflowEnvironment;
  let client: Client;
  let worker: Worker;
  let workerRun: Promise<void> | undefined;
  let delayedActivityStarted = false;
  let releaseDelayedActivity!: () => void;
  let finishDelayedActivity!: () => void;
  const delayedActivityRelease = new Promise<void>(resolve => { releaseDelayedActivity = resolve; });
  const delayedActivityFinished = new Promise<void>(resolve => { finishDelayedActivity = resolve; });
  const taskQueue = `email-engine-${randomUUID()}`;

  beforeAll(async () => {
    environment = await TestWorkflowEnvironment.createTimeSkipping();
    client = environment.client;
    worker = await Worker.create({
      connection: environment.nativeConnection,
      taskQueue,
      workflowsPath: path.resolve(__dirname, '../../workflows/test-email-workflow.ts'),
      shutdownGraceTime: '1s',
      activities: {
        generateTemporaryPassword,
        sendWelcomeEmail: async (input: SendWelcomeEmailActivityInput) => {
          if (input.tenantName === 'Timeout Test Tenant') {
            delayedActivityStarted = true;
            // Keep the activity pending until the test observes the deadline.
            // A release barrier leaves no activity timer or test-service sleep
            // RPC behind when result() re-locks the time-skipping clock.
            try {
              await delayedActivityRelease;
              return await sendWelcomeEmail(input);
            } finally {
              finishDelayedActivity();
            }
          }
          return sendWelcomeEmail(input);
        },
      },
    });
    workerRun = worker.run();
    // Observe early rejection immediately; teardown still propagates failure.
    workerRun.catch(() => {});
  });

  afterAll(async () => {
    try {
      if (worker) { worker.shutdown(); await workerRun; }
    } finally {
      await environment?.teardown();
      vi.unstubAllEnvs();
    }
  });

  describe('End-to-End Email Workflow', () => {
    it('should execute complete email workflow with password generation', async () => {
      const timestamp = Date.now();
      const input: SendWelcomeEmailActivityInput = {
        tenantId: `tenant-${timestamp}`,
        tenantName: 'E2E Test Tenant',
        adminUser: {
          userId: `user-${timestamp}`,
          email: `e2e-test-${timestamp}@example.com`,
          firstName: 'E2E',
          lastName: 'Test',
        },
        temporaryPassword: '', // Will be generated by workflow
        clientName: 'E2E Test Client',
        loginUrl: 'https://e2e-test.example.com/login',
      };

      // Execute the workflow end-to-end
      const handle = await client.workflow.start(testEmailWorkflow, {
        args: [input],
        taskQueue,
        workflowId: `email-e2e-test-${timestamp}`,
      });

      const result = await handle.result();

      // Verify password was generated
      expect(result.temporaryPassword).toBeDefined();
      expect(result.temporaryPassword).toHaveLength(12);
      expect(result.temporaryPassword).toMatch(/[A-Z]/);
      expect(result.temporaryPassword).toMatch(/[a-z]/);
      expect(result.temporaryPassword).toMatch(/[2-9]/);
      expect(result.temporaryPassword).toMatch(/[!@#$%^&*]/);
      expect(result.temporaryPassword).not.toMatch(/[0O1lI]/);

      // Verify email was sent
      expect(result.emailResult.emailSent).toBe(true);
      expect(result.emailResult.messageId).toBeDefined();
      expect(result.emailResult.messageId).toMatch(/^mock-/);
      expect(result.emailResult.error).toBeUndefined();
    });

    it('should handle workflow with invalid email gracefully', async () => {
      const timestamp = Date.now();
      const input: SendWelcomeEmailActivityInput = {
        tenantId: `tenant-${timestamp}`,
        tenantName: 'Invalid Email Test',
        adminUser: {
          userId: `user-${timestamp}`,
          email: 'invalid-email-format',
          firstName: 'Invalid',
          lastName: 'Test',
        },
        temporaryPassword: '',
        clientName: 'Invalid Email Client',
      };

      const handle = await client.workflow.start(testEmailWorkflow, {
        args: [input],
        taskQueue,
        workflowId: `email-invalid-${timestamp}`,
      });

      const result = await handle.result();

      // Password should still be generated
      expect(result.temporaryPassword).toBeDefined();
      expect(result.temporaryPassword).toHaveLength(12);

      // Email should fail gracefully
      expect(result.emailResult.emailSent).toBe(false);
      expect(result.emailResult.error).toBeDefined();
      expect(result.emailResult.error).toContain('Invalid email address');
    });

    it('should execute workflow with minimal required fields', async () => {
      const timestamp = Date.now();
      const input: SendWelcomeEmailActivityInput = {
        tenantId: `tenant-${timestamp}`,
        tenantName: 'Minimal Test Tenant',
        adminUser: {
          userId: `user-${timestamp}`,
          email: `minimal-${timestamp}@example.com`,
          firstName: 'Minimal',
          lastName: 'User',
        },
        temporaryPassword: '',
        // No clientName or loginUrl - should use defaults
      };

      const handle = await client.workflow.start(testEmailWorkflow, {
        args: [input],
        taskQueue,
        workflowId: `email-minimal-${timestamp}`,
      });

      const result = await handle.result();

      // Should complete successfully with defaults
      expect(result.temporaryPassword).toBeDefined();
      expect(result.emailResult.emailSent).toBe(true);
      expect(result.emailResult.messageId).toBeDefined();
      expect(result.emailResult.error).toBeUndefined();
    });

    it('should handle multiple concurrent workflows', async () => {
      const timestamp = Date.now();
      const workflows = [];

      // Start 3 concurrent workflows
      for (let i = 0; i < 3; i++) {
        const input: SendWelcomeEmailActivityInput = {
          tenantId: `tenant-${timestamp}-${i}`,
          tenantName: `Concurrent Test Tenant ${i}`,
          adminUser: {
            userId: `user-${timestamp}-${i}`,
            email: `concurrent-${timestamp}-${i}@example.com`,
            firstName: `User${i}`,
            lastName: 'Test',
          },
          temporaryPassword: '',
          clientName: `Concurrent Client ${i}`,
        };

        const handle = await client.workflow.start(testEmailWorkflow, {
          args: [input],
          taskQueue,
          workflowId: `email-concurrent-${timestamp}-${i}`,
        });

        workflows.push(handle);
      }

      // Wait for all workflows to complete
      const results = await Promise.all(workflows.map(h => h.result()));

      // Verify all workflows completed successfully
      results.forEach((result, index) => {
        expect(result.temporaryPassword).toBeDefined();
        expect(result.temporaryPassword).toHaveLength(12);
        expect(result.emailResult.emailSent).toBe(true);
        expect(result.emailResult.messageId).toBeDefined();
      });

      // Verify all passwords are unique
      const passwords = results.map(r => r.temporaryPassword);
      const uniquePasswords = new Set(passwords);
      expect(uniquePasswords.size).toBe(3);
    });
  });

  describe('Workflow Error Handling', () => {
    it('should complete workflow even if email fails', async () => {
      const timestamp = Date.now();
      const input: SendWelcomeEmailActivityInput = {
        tenantId: `tenant-${timestamp}`,
        tenantName: 'Error Handling Test',
        adminUser: {
          userId: `user-${timestamp}`,
          email: '', // Empty email to trigger error
          firstName: 'Error',
          lastName: 'Test',
        },
        temporaryPassword: '',
      };

      const handle = await client.workflow.start(testEmailWorkflow, {
        args: [input],
        taskQueue,
        workflowId: `email-error-${timestamp}`,
      });

      // Workflow should complete without throwing
      const result = await handle.result();

      // Password generation should still work
      expect(result.temporaryPassword).toBeDefined();
      expect(result.temporaryPassword).toHaveLength(12);

      // Email should fail but not crash workflow
      expect(result.emailResult.emailSent).toBe(false);
      expect(result.emailResult.error).toBeDefined();
    });

    it('rejects when the email activity exceeds the workflow execution deadline', async () => {
      const timestamp = Date.now();
      const input: SendWelcomeEmailActivityInput = {
        tenantId: `tenant-${timestamp}`,
        tenantName: 'Timeout Test Tenant',
        adminUser: {
          userId: `user-${timestamp}`,
          email: `timeout-${timestamp}@example.com`,
          firstName: 'Timeout',
          lastName: 'Test',
        },
        temporaryPassword: '',
      };

      // Create workflow with short timeout to test timeout handling
      const handle = await client.workflow.start(testEmailWorkflow, {
        args: [input],
        taskQueue,
        workflowId: `email-timeout-${timestamp}`,
        workflowExecutionTimeout: '1s',
      });

      try {
        await expect.poll(() => delayedActivityStarted).toBe(true);
        // Advance server time explicitly while the activity is held. Await the
        // sleep RPC before result() so its clock lock cannot strand that RPC.
        await environment.sleep(2_000);
        expect((await handle.describe()).status.name).toBe('TIMED_OUT');
        await expect(handle.result()).rejects.toMatchObject({ cause: { name: 'TimeoutFailure' } });
      } finally {
        releaseDelayedActivity();
        if (delayedActivityStarted) await delayedActivityFinished;
      }
    });
  });
});
